### ISSUE TITLE
Add an example with minibatching for sciml_train

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#133]
Currently none of the README examples showcase how to minibatch. It would be a good thing to teach users.

**Comment by ali-ramadhan** [comment]
I need to learn how to do this so maybe I can take a stab at this.

I guess I could just take the existing Lotka-Volterra neural ODE example and mini-batch inside the loss function if that's the approach to take?

I also have a few notebooks where I'm training a simple diffusion neural PDE that might make for a decent example, but still playing around with new ideas there: https://github.com/ali-ramadhan/neural-differential-equation-climate-parameterizations/blob/master/diffusion_equation/Diffusion%20neural%20PDE%20and%20DAE.ipynb

**Comment by cems2** [comment]
See #167 this does a batch but doesn't rotate the batches.  But one could build around that template using the new optional data arg to feed minibatches.

**Comment by ChrisRackauckas** [comment]
We do have an example in the docs now so I'll close this, but we can definitely keep improving it.
