### ISSUE TITLE
NeuralODE: modeling dynamics of system with (discontinuous) control inputs

### ISSUE THREAD

**Issue by saihv** [SciML/DiffEqFlux.jl#190]
I am trying to investigate the applicability of neural ODEs to system ID under actuation. Essentially, if my system can be described as `x_dot = f(x, u)`, given `x_o` and `u`, I would like to predict the evolution of x. Sort of like what [SINDYc](https://arxiv.org/abs/1605.06682) attempts to do. 

My question is two-fold: firstly, is it possible to also include time-dependent control inputs in the neural ODE formulation? Is it straightforward enough to just "stack" an input value along with the state being passed to the neural network (depending on the value of `t` being considered), under the hope that the NN will figure out the relationship between x and u?

Secondly, for systems such as the inverted pendulum on a cart, the input can just be a relay-type input, where a force is applied only for a period of time. Would such a discontinuity be a problem?

**Comment by ChrisRackauckas** [comment]
Yes. https://github.com/JuliaDiffEq/DiffEqFlux.jl/issues/174 is somewhat an example, though I would use a spline from DataInterpolations instead of a neural network there, but you get the point.

**Comment by ChrisRackauckas** [comment]
>Secondly, for systems such as the inverted pendulum on a cart, the input can just be a relay-type input, where a force is applied only for a period of time. Would such a discontinuity be a problem?

You might want to declare the discontinuity via `d_discontinuity` or `ContinuousCallback`, but that's mostly an optimization. You'll find a lot of discussions around on how to do this, but feel free to ask for more details if necessary.

**Comment by saihv** [comment]
Thank you, will try them out! Ideally I'd like to see a sufficiently trained model generalizing to different inputs by finding the right 'decoupling' in the equations (hence the NN instead of just fitting)

**Comment by ChrisRackauckas** [comment]
I'm not sure what you mean about that?

**Comment by saihv** [comment]
I am trying to see if it's possible to train a black box that takes as inputs an initial state x0 and control signal info (arbitrary `u` applied for time period `t`) and approximates the long term evolution of the system.

**Comment by ChrisRackauckas** [comment]
Yes, and we've added an example to the README. Making it discontinuous will have local minima though, so you have to be careful how you optimize that.
