### ISSUE TITLE
FastChain adjoint definition is not compatible with acting on a matrix

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#192]
It's written for the common action against a vector, but we could in theory have it support a matrix if someone took a good look at it.

**Comment by ChrisRackauckas** [comment]
@dhairyagandhi96 could you take a look at this?

**Comment by dhairyagandhi96** [comment]
If structure is important could we not just use the generic `Chain` and get the speed up via tracing, and optimisation on structures directly like we plan on doing in `Functors.jl`.

**Comment by dhairyagandhi96** [comment]
I can take a look at it

**Comment by ChrisRackauckas** [comment]
>If structure is important could we not just use the generic Chain and get the speed up via tracing, and optimisation on structures directly like we plan on doing in Functors.jl.

Indeed, we could in theory in the future. But for now, it probably would take an hour or so to get an optimal adjoint definition that supports matrix data, so we might as well fix it and then use it as a test case for optimality of whatever automated tooling comes along. 

The only issue really is that

https://github.com/SciML/DiffEqFlux.jl/blob/master/src/fast_layers.jl#L58-L69

assumes `ybar` is a vector, so it shouldn't be too difficult to fix that. Then when someone obsoletes it in a few years, yeah, let's delete it, but for now we should get the 99% case as good as we can.

**Comment by ChrisRackauckas** [comment]
Awesome, the fix in https://github.com/SciML/DiffEqFlux.jl/pull/246 gives a real-world speedup of 3.5x by being able to change to that form.

**Comment by dhairyagandhi96** [comment]
Sorry I got side tracked with this issue, I had assumed I had sent a PR for it 😅😶

FWIW, I had changed  https://github.com/SciML/DiffEqFlux.jl/blob/c7b1bf322ae3fe6a0b5ccdc32636c7408e9bd460/src/fast_layers.jl#L68 to `sum(bbar, dims = 2)`

**Comment by ChrisRackauckas** [comment]
Great! That's the same thing I came up with, so it sounds like we're good.
