### ISSUE TITLE
Outer vs Inner constructors style

### ISSUE THREAD

**Issue by Emmanuel-R8** [SciML/DiffEqFlux.jl#230]
The function definitions in neural_de.jl are within each model's `struct`.

As an unfortunate consequence, when docstrings are written before those functions, they are considered as docstrings relating to the struct and not the function. In other words, when docs are automatically generated, those docstrings appear as _type_ descriptions and not _function_ description.

Is it typically the case that constructors appear within type descriptions (in which case the above is irrelevant)? But I find that unnatural.

_Bonus points_: why is NeuralCDDE, unlike all others, defined outside its `struct`?

**Comment by ChrisRackauckas** [comment]
>Is it typically the case that constructors appear within type descriptions (in which case the above is irrelevant)? But I find that unnatural.

It depends on whether it's an inner or outer constructor. We should probably make them all outer constructors. Then we should give each of them a docstring, and make the https://github.com/SciML/DiffEqFlux.jl/blob/master/docs/src/API.md page just be all of these docstrings.

**Comment by Emmanuel-R8** [comment]
Are you OK if I have a crack at "outing" the constructors in the same commit as the docstrings?

**Comment by ChrisRackauckas** [comment]
Note that I added the docstrings in https://github.com/SciML/DiffEqFlux.jl/pull/232 . Feel free to edit them in the same commit though.

**Comment by ChrisRackauckas** [comment]
As noted in https://github.com/SciML/DiffEqFlux.jl/pull/236, the reason for the inner constructors is because if we make them outer constructors we have ambiguity against the default outer constructor, so this is fixed by taking over the default. Thus NeuralCDDE should probably be made an inner just for consistency.

**Comment by ChrisRackauckas** [comment]
Thanks for pointing out this issue. It's been fixed up and now things are for the better!
