### ISSUE TITLE
Google season of Docs

### ISSUE THREAD

**Issue by sanyadeveloper2000** [SciML/DiffEqFlux.jl#237]
I find your project really exciting and want to contribute as a technical writer.
I meet the eligibility criteria and would like to give it a try.
Can you please explain the detailed process of contribution.
Thanks

**Comment by ChrisRackauckas** [comment]
Hey, thanks for your interest. You should join our discussions in #machine-learning and #diffeq-bridged on the JuliaLang slack. To get an invite, check out https://slackinvite.julialang.org/ . I think some tutorials and documentation which describe minibatching could be a great place to start.

**Comment by sanyadeveloper2000** [comment]
Hi
I have joined the discussions  in #machine-learning and #diffeq-bridged on the JuliaLang slack. I am currently going through the tutorials and will keep you updated with the progress.

Thankyou.

**Comment by ChrisRackauckas** [comment]
I opened a list of things that could be done at https://github.com/SciML/DiffEqFlux.jl/issues/244, so we can discuss in more detail there.
