### ISSUE TITLE
FYI only - Interesting paper on "Differentiation of Blackbox Combinatorial Solvers"

### ISSUE THREAD

**Issue by Emmanuel-R8** [SciML/DiffEqFlux.jl#239]
This seems complementary to DiffEqFlux

[Differentiation of Blackbox Combinatorial Solvers](https://arxiv.org/abs/1912.02175)

**Comment by ChrisRackauckas** [comment]
I'm going to close this sense its outside the scope of DiffEqFlux (no diffeqs), but indeed it's interesting and complementary. Thanks for sharing!
