### ISSUE TITLE
[Bug Report] Rosenbrock23 gives no method matching finite_difference_jacobian

### ISSUE THREAD

**Issue by jiweiqi** [SciML/DiffEqFlux.jl#257]
I am following the example of neural ode. The code works well with ode solver of `Tsit5()` and `CVODE_BDF`. However, the solver of `Rosenbrock23(autodiff=false)` not working. Since I am working with very stiff ode, so that a stable solver is preferred.

Giving the following error: here is the [notebook](https://github.com/jiweiqi/Transfer/blob/master/diffeq_adjoint_case1_test.ipynb)

> MethodError: no method matching finite_difference_jacobian(::DiffEqBase.UDerivativeWrapper{ODEFunction{false,typeof(dudt),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Float64,Array{Float32,1}}, ::Array{Float64,1}, ::Type{Val{:forward}}, ::Type{Float64}, ::Array{Float32,1}; dir=true, colorvec=1:5, sparsity=nothing, jac_prototype=nothing)
Closest candidates are:
  finite_difference_jacobian(::Any, ::AbstractArray{#s76,N} where N where #s76<:Number, ::Type{T1}, ::Type{T2}) where {T1, T2} at /home/jiweiqi/.julia/packages/FiniteDiff/cB7yD/src/jacobians.jl:138 got unsupported keyword arguments "dir", "colorvec", "sparsity", "jac_prototype"
  finite_difference_jacobian(::Any, ::AbstractArray{#s75,N} where N where #s75<:Number, ::Type{T1}, ::Type{T2}, !Matched::Union{Nothing, AbstractArray{#s74,N} where N where #s74<:T2}; relstep, absstep, colorvec, sparsity, jac_prototype, dir) where {T1, T2} at /home/jiweiqi/.julia/packages/FiniteDiff/cB7yD/src/jacobians.jl:138
  finite_difference_jacobian(::Any, ::AbstractArray{#s77,N} where N where #s77<:Number, ::Type{T1}) where T1 at /home/jiweiqi/.julia/packages/FiniteDiff/cB7yD/src/jacobians.jl:138 got unsupported keyword arguments "dir", "colorvec", "sparsity", "jac_prototype"
  ...

**Comment by ChrisRackauckas** [comment]
```julia
using DiffEqSensitivity, OrdinaryDiffEq, Zygote
using Flux
using Flux: Params, gradient, mse, glorot_normal, throttle
using DiffEqFlux
using Sundials
function case1_ode(dydt, y, k, t)
  dydt[1] = -2 * k[1] * y[1]^2 - k[2] * y[1]
  dydt[2] = k[1] * y[1]^2 - k[4] * y[2] * y[4]
  dydt[3] = k[2] * y[1] - k[3] * y[3]
  dydt[4] = k[3] * y[3] - k[4] * y[2] * y[4]
  dydt[5] = k[4] * y[2] * y[4]
end

k = Float32[0.1, 0.2, 0.13, 0.3]
u0 = Float32[1.0;1.0;0.0;0.0;0.0]
tspan = (0f0,20f0)
alg = Rosenbrock23(autodiff=false)

prob_trueode = ODEProblem(case1_ode,u0,tspan,k)
sol_trueode = concrete_solve(prob_trueode,alg)

using Plots
plot(sol_trueode)

t = sol_trueode.t
ode_data = Array(sol_trueode)

dudt2 = Chain(x -> log.(clamp.(x, 1e-30, 10)),
              Dense(5, 3, exp),
              Dense(3, 5))

dudt2.layers[2].W .= clamp.(dudt2.layers[2].W, 0, 4)

p,re = Flux.destructure(dudt2) # use this p as the initial condition!

dudt(u,p,t) = re(p)(u) # need to restrcture for backprop!

prob_crnn = ODEProblem(dudt,Float32.(u0),tspan)

function predict_n_ode()
  Array(concrete_solve(prob_crnn,alg,u0,p,saveat=t))
end

function loss_n_ode()
    pred = predict_n_ode()
    loss = sum(abs2,ode_data .- pred)
    loss
end

loss_n_ode() # n_ode.p stores the initial parameters of the neural ODE
```

Works. It's because you were mixing Float32 values and Float64 values. If it's all Float32 or all Float64 you're fine.

**Comment by YingboMa** [comment]
It looks like there is a missing method in `finite_difference_jacobian`. We might want to support mixed-precision or at least give a more informative error message.

**Comment by ChrisRackauckas** [comment]
Indeed that could be a good thing to do.
