### ISSUE TITLE
Indexing solution in loss function gives zero gradient with default sensealg

### ISSUE THREAD

**Issue by caryan** [SciML/DiffEqFlux.jl#259]
I have a loss function that only depends on some outputs of an ODE. If I index into the solution in my loss function the gradient returns zeros whereas if I use a mask instead then life is good. Using `sensealg=ForwardDiffSensitivity` works with either version of the loss function. 

Taking a toy example of resonant driving of a two level quantum system where the equations look something like (after doing the usual complex -> real trick)
```
4-element Array{Equation,1}:
 Equation(derivative(ψ₁(t), t), (ωq * 0.5) * ψ₃(t) + (A * cos(ωd * t)) * (1.0 * ψ₄(t)))
 Equation(derivative(ψ₂(t), t), (ωq * -0.5) * ψ₄(t) + (A * cos(ωd * t)) * (1.0 * ψ₃(t)))
 Equation(derivative(ψ₃(t), t), (ωq * -0.5) * ψ₁(t) + (A * cos(ωd * t)) * (-1.0 * ψ₂(t)))
 Equation(derivative(ψ₄(t), t), (ωq * 0.5) * ψ₂(t) + (A * cos(ωd * t)) * (-1.0 * ψ₁(t)))
```

and I care only about the population minimizing the population of the ground state at some point in time `|ψ₁(t) + 1imψ₃(t)|^2

```
function loss(p)
    sol = Array(concrete_solve(prob, Tsit5(), ψ₀, p, saveat=tspan[2], save_start=false))
    sum(abs2, sol[[1,3]])
#     sum(abs2, sol .* [1; 0; 1; 0])
end

gradient(loss, [1.0, 1.0, 0.01])

([0.0, 0.0, 0.0],)
```

**Comment by ChrisRackauckas** [comment]
I think this is an issue with `save_idxs` that I found today and realized it's a bigger deal than I thought. `concrete_solve` with `save_idxs` needs a few more fixes.

 https://github.com/SciML/DiffEqSensitivity.jl/issues/222

**Comment by ChrisRackauckas** [comment]
Should be good now
