### ISSUE TITLE
reconstruct_Foo instead of reconstruct NeuralODE

### ISSUE THREAD

**Issue by metanoid** [SciML/DiffEqFlux.jl#264]
Maybe I just don't understand functors, in which case please close this issue.

But it seems odd to me that on this line, the name of the returned object is `reconstruct_Foo` rather than `reconstruct_NeuralODE`

https://github.com/SciML/DiffEqFlux.jl/blob/dceff374e5fff15c732685df3c69aa2c27102260/src/neural_de.jl#L69

Logging an issue in case it needs review

**Comment by ChrisRackauckas** [comment]
Oh, those functor definitions can be completely removed. They are overridden by https://github.com/SciML/DiffEqFlux.jl/blob/master/src/neural_de.jl#L3 , so Zygote doesn't end up caring about our functor definitions.
