### ISSUE TITLE
RadauAII5 and typeassert issues in autodiff

### ISSUE THREAD

**Issue by ermalrrapaj** [SciML/DiffEqFlux.jl#271]
Hi,
I am new to Julia and OrdinaryDiffEq so I'm probably missing a step but I need to use RadauIIA5 as my ODE is stiff. I am doing parameter estimation so I need the gradient of the loss function
with respect to the parameters, however I get the following error:
"TypeError: in typeassert, expected Float64, got ForwardDiff.Dual{Nothing,Float64,1}"
By searching on various  threads  I found out that I need to do some type conversion as when during autodiff things are not working right for me.
To reproduce my error I am providing the following example:

```julia
using ImportMacros
@import DifferentialEquations as DE
@import Flux as FL
@import DiffEqFlux as DEFL
@import DiffEqSensitivity as DES

function lotka_volterra(du, u, p, t)
  x, y = u
  α, β, δ, γ = p
  du[1] = dx = α * x - β * x * y
  du[2] = dy = -δ * y + γ * x * y
end
u0 = [1.0,1.0];
tspan = (0.0,10.0);
p0 = [1.5,1.0,3.0,1.0];
maxiters=10000;
prob0 = DE.ODEProblem(lotka_volterra,u0,tspan,p0);
# Solve the ODE and collect solutions at fixed intervals
target_data = DE.solve(prob0,DE.RadauIIA5(), saveat =  0:0.5:10.0,iter=maxiters,tol=10.0^(-6));
loss_function = function(p)
    prob = DE.remake(prob0;u0=convert.(eltype(p),prob0.u0),p=p)
    prediction = DE.concrete_solve(prob, DE.RadauIIA5(),u0, p; saveat = 0.0:0.5:10.0,iter=maxiters,tol=10.0^(-6))

    tmpdata=prediction[[1,2],:];
    tdata=target_data[[1,2],:];

    # Calculate squared error
    return sum(abs2,tmpdata-tdata)
end
p=[1.5,1.2,1.4,1.6];
FL.gradient(loss_function,p)
```

Is there a conversion I am missing somewhere? I would not like to use autodiff=false if possible.

**Comment by ChrisRackauckas** [comment]
It's a Zygote bug. You need to do `DE.RadauIIA5(autodiff=false)` for now until Zygote is fixed. But if you're not using a GPU it shouldn't have a big impact on performance since the Jacobian is forward mode anyways (since it's square): you just lose the chunking.

**Comment by ChrisRackauckas** [comment]
I found a fix.

**Comment by ermalrrapaj** [comment]
Hi,
Thank you for you help.
I'm 'hacking' it for now by doing Forwardiff.gradient on the loss and also @adjoint from Zygote to avoid autodiff=false. But a fix would be great.

**Comment by ChrisRackauckas** [comment]
Out of curiousity, what's the need for avoiding `autodiff=false` there?

**Comment by ermalrrapaj** [comment]
Hi,
I naively thought I needed autodiff =true to perform training. For now I am just optimizing for some parameters, but I plan to use a neural network instead of the parameter eventually to account for the unknown part of my problem. In the example of the Lotka-Volterra, p would be a neural network so it would be effective a function of time to train. 
Can I still train the neural network with autodiff=false?

**Comment by ChrisRackauckas** [comment]
>Can I still train the neural network with autodiff=false?

Yes, using autodiff at that part isn't all that related to whether it's using a fast autodiff for the gradient. In this examples there are 3 entirely separate ways autodiff is being layered.

**Comment by ermalrrapaj** [comment]
Thank you for your help.

**Comment by ChrisRackauckas** [comment]
This long standing issue has been fixed. Thanks for the report. This has also been used to make tests for each of the methods.
