### ISSUE TITLE
Augmented neural ODEs

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#288]
https://arxiv.org/abs/1904.01681

**Comment by avik-pal** [comment]
Regarding adding a layer for this work, I was wondering if we need to have a new layer `AugmentedNeuralODE`. Or should we simply modify the `NeuralODE` type to store a parameter `augment_dim`, and dispatch based on that to use the current version if it is 0.

**Comment by ChrisRackauckas** [comment]
Yeah, that's a good question. A keyword argument for the number of augmentation dimensions is probably all that's needed, and is easy to generalize to all of the other NDE layers

**Comment by avik-pal** [comment]
Another simpler alternative might be to define a function like
```
augment(nde<:NeuralDELayer, adim::Int) = Chain((x, p) -> augment(x, Val(adim)), nde) 
```

This should allow the augmentation to work with all the existing layers, without modifying them at all.

**Comment by ChrisRackauckas** [comment]
But I think you still might need to modify the equations per-DE? Give it a try and see if it can work.

**Comment by avik-pal** [comment]
I see. I tried the Concentric Circles experiment from the paper (using NeuralODE) and it seems to work as expected.

![Neural ODE](https://user-images.githubusercontent.com/30564094/84695274-35113080-af68-11ea-8558-1d0d3e3188cb.png)
Neural ODE

![Augmented Neural ODE](https://user-images.githubusercontent.com/30564094/84695279-36425d80-af68-11ea-86b3-f6369f1b98a9.png)
Augmented Neural ODE

I will try out the other DE layers, and open a PR soon.
