### ISSUE TITLE
ANODEV2

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#289]
https://arxiv.org/abs/1906.04596

**Comment by Biswajitghosh98** [comment]
[Pytorch code](https://github.com/amirgholami/anode) for reference

**Comment by ChrisRackauckas** [comment]
I just realized there's nothing to do here. It's just `sensealg = TrackerAdjoint()` or `sensealg = ReverseDiffAdjoint()` for discretize the optimize, and then it's `sensealg = InterpolatingAdjoint()` (the default) to do the checkpointing style. So I'm going to close this since it's just a differentiation choice and no work needs to be done.
