### ISSUE TITLE
Neural Stochastic DiffEq example no longer working

### ISSUE THREAD

**Issue by cmhyett** [SciML/DiffEqFlux.jl#336]
Following neural_sde.md line-by-line results in an error when invoking DiffEqFlux.sciml_train:

ERROR: MethodError: no method matching Float32(::Tracker.TrackedReal{Float32})
Closest candidates are:
  Float32(::Real, ::RoundingMode) where T<:AbstractFloat at rounding.jl:200
  Float32(::T) where T<:Number at boot.jl:718
  Float32(::Int8) at float.jl:60

As this error is quite deep, I've had trouble tracing it. Help would be appreciated!

**Comment by ChrisRackauckas** [comment]
Are you on Julia v1.4?

**Comment by ChrisRackauckas** [comment]
I just ran it and it's working fine... so I'll close this. My guess is you're not running Julia v1.4 or DiffEqFlux v1.16, in which case, everything should be fine if you update.

**Comment by cmhyett** [comment]
Yep, julia 1.3 was the issue. Thanks!

**Comment by cmhyett** [comment]
To throw a bit more light on the issue for those stuck with julia 1.3, this seems to be the same issue as
https://discourse.julialang.org/t/optimizing-parameters-of-ode-in-diffeqflux-not-implemented-convert-tracked-tracker-trackedreal-float64-to-tracked-float64/22560
Changing the sensealg in the construction of the NeuralSDE is a workaround. See neural_de.jl for details on the constructor and 
https://docs.sciml.ai/stable/analysis/sensitivity/
for details on alternative sensitivity routines.

**Comment by ChrisRackauckas** [comment]
Great! Good to hear.
