### ISSUE TITLE
Rename DiffEqFlux?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#354]
I have gotten a lot of inquiries about renaming the package to UniversalDiffEq.jl or even SciML.jl, so I wanted to gather the opinions here.

**Comment by ViralBShah** [comment]
If this is closely related to the UDE paper, and an implementation of those ideas, that seems like the natural name.

**Comment by ali-ramadhan** [comment]
I guess UniversalDiffEq.jl suggests that the package is part of the DifferentialEquations.jl family while SciML.jl suggests that it's not. Although it seems it's all under the SciML organization now.

**Comment by ViralBShah** [comment]
The DiffEq is the Sci in SciML I suppose. If you want to emphasize more of the ML part of the algorithm, I guess the trend nowadays is to pick something that ends in `Net`, and includes a scientific name in the front - like EulerNet or something.

**Comment by ViralBShah** [comment]
Thoughts?

**Comment by ChrisRackauckas** [comment]
Either UniversalDiffEq.jl or SciML.jl I think.

**Comment by ViralBShah** [comment]
I don't think you should use SciML.jl.

**Comment by ric-cioffi** [comment]
Maybe DiffEqML.jl ? That would keep the link with both DifferentialEquations and SciML.
Just my two cents :)

**Comment by ViralBShah** [comment]
That's a good one. But since this clearly goes with the UDE paper, I think it should have the same name as the algorithm. We already picked a good name for the paper - why pick a different name here?

**Comment by ChrisRackauckas** [comment]
It's just the Flux/Lux bits now.
