### ISSUE TITLE
More pictures

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#375]
![sde_moment_fit](https://user-images.githubusercontent.com/1814174/88511872-97bc0a00-cfb3-11ea-9d44-a3ed96a77df9.png)
![sdeplot](https://user-images.githubusercontent.com/1814174/88511873-97bc0a00-cfb3-11ea-8cf5-5930b6575d9d.png)

**Comment by ChrisRackauckas** [comment]
![neural_ode](https://user-images.githubusercontent.com/1814174/88589293-e8207f80-d026-11ea-86e2-8a3feb8252ca.gif)

**Comment by ChrisRackauckas** [comment]
![plot_hybrid](https://user-images.githubusercontent.com/1814174/91687561-08fc5900-eb2e-11ea-9f26-6b794e1e1248.gif)

**Comment by Vaibhavdixit02** [comment]
![BayesianNODE_NUTS_ChainPlot2](https://user-images.githubusercontent.com/23134958/102398102-dacf5600-4004-11eb-853a-60faa67422ef.png)
![BayesianNODE_NUTS_ChainPlot1](https://user-images.githubusercontent.com/23134958/102398106-dd31b000-4004-11eb-9623-a24ab0409b07.png)
![BayesianNODE_NUTS_ContourPlot](https://user-images.githubusercontent.com/23134958/102398114-defb7380-4004-11eb-835e-84f1519648dc.png)
![BayesianNODE_NUTS_TimeSeriesPlot](https://user-images.githubusercontent.com/23134958/102398119-df940a00-4004-11eb-9cdb-eb7be8724dd3.png)

**Comment by Vaibhavdixit02** [comment]
![BayesianNODE_SGLD_Plot2](https://user-images.githubusercontent.com/23134958/102398740-b162fa00-4005-11eb-9778-ae16a267a257.png)
![BayesianNODE_SGLD_Plot1](https://user-images.githubusercontent.com/23134958/102398744-b2942700-4005-11eb-93e9-7f045d8494ce.png)

**Comment by YingboMa** [comment]
![rober_fitting](https://user-images.githubusercontent.com/17304743/102832372-28a8dd00-43bc-11eb-93de-36166e8b17cf.png)
