### ISSUE TITLE
sciml_train crashes when fed Fluxs ::Params type

### ISSUE THREAD

**Issue by jc-audet** [SciML/DiffEqFlux.jl#379]
Hello, this is my first issue on Github, sorry in advance if I'm missing some information or something.

I'm trying to use sciml_train function in order to train a Flux model, but run into an error when passing Fluxs ::Params type as parameters to the function.

```
ps = Flux.params(model)
DiffEqFlux.sciml_train(loss, ps, opt, data; cb = cb)
```
`ERROR: MethodError: no method matching copy(::Params)`

Looking at the function I saw that it ends up using Flux.params() anyway with the fed parameters

```
function sciml_train(loss, _θ, opt, _data = DEFAULT_DATA; cb = (args...) -> false, maxiters = get_maxiters(data), progress=true, save_best=true)
    θ = copy(_θ)
    ps = Flux.params(θ)
    
    #rest of function
```

Would checking if the fed parameters to the function are already Flux parameters (::Params) be a good addition to this function?

**Comment by ChrisRackauckas** [comment]
>Would checking if the fed parameters to the function are already Flux parameters (::Params) be a good addition to this function?

Yeah, why not. Params won't work in other optimizers though, but we might as well make this one not fail in a case where we know it would.

**Comment by ChrisRackauckas** [comment]
sciml_train has been removed and deprecated for direct Optimization.jl usage
