### ISSUE TITLE
Handling sol.u interface

### ISSUE THREAD

**Issue by ClydeHuibregtse** [SciML/DiffEqFlux.jl#389]
This code
```
function lv!(du, u, p, t)
    x,y = u
    a, b, c, d = p
    du[1] = a*x - b*x*y
    du[2] = -c*y + d*x*y
end
function test()
    u0 = [1.,1.]
    p = [1.,1.,1.,1.]
    tspan = [0.,1.]
    prob = ODEProblem(lv!, u0, tspan, p)
    sol = solve(prob)
    return sol.u[end][1]
end
gradient(test)
```

throws an error due to the "sol.u" use. Either updating the usage or handling the ".u" interface would be greatly appreciated!

**Comment by ChrisRackauckas** [comment]
Fixed in https://github.com/SciML/DiffEqSensitivity.jl/pull/325 which should be merged over the weekend, but the general recommendation is still to not use `sol.u[end][1]` and instead just directly use `sol[end][1]`, but it's good to have covered this case.
