### ISSUE TITLE
DDE Example leads to " StackOverflowError:"

### ISSUE THREAD

**Issue by RobWalt** [SciML/DiffEqFlux.jl#396]
Can anyone confirm this isn't just me? (I tested it on two separate machines.)

The example I'm talking about is [this one](https://github.com/SciML/DiffEqFlux.jl/blob/master/docs/src/examples/delay_diffeq.md).

I've already tried to set `maxiters` to some value as low as only 5, but it did nothing.

**Comment by ChrisRackauckas** [comment]
ReverseDiffAdjoint should do better so I updated the docs. https://github.com/SciML/DiffEqFlux.jl/commit/ce1f153ab57ba6067f8e61648be8aee1deb905c2

**Comment by ChrisRackauckas** [comment]
Yes, it needs a DiffEqSensitivity patch. Update packages with `]up` and you should be good.

**Comment by RobWalt** [comment]
It works! I'm totally stoked! Thank you very much for the fast help and for your work in general!
