### ISSUE TITLE
Update Neural SDE documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#402]
https://github.com/SciML/DifferentialEquations.jl/issues/661 mentions a few things, like parallelized ensembles and ReverseDiffAdjoint, which should be used in the neural SDE example. This would be a great thing to update.

**Comment by duynht** [comment]
Hi @ChrisRackauckas 
I would like to try this issue

**Comment by ChrisRackauckas** [comment]
alright cool thanks!

**Comment by aditya-2020** [comment]
Hi @ChrisRackauckas 
Myself Aditya Saxena, I am an ECE 2nd year student at IIT BHU. I am a GSoC'21 aspirant and wish to contribute to the SciML community. If this issue is still open then I wish to work on this issue.

**Comment by ChrisRackauckas** [comment]
This issue is pretty complete. Sorry. There's some others to look at. Try your hand at implementing https://github.com/SciML/DiffEqFlux.jl/issues/422
