### ISSUE TITLE
Link to stable documentation broken

### ISSUE THREAD

**Issue by dev10110** [SciML/DiffEqFlux.jl#407]
The link to the stable documentation in the GitHub readme seems broken. 

I hope someone can fix this :)

**Comment by ChrisRackauckas** [comment]
@kanav99 this one keeps disappearing.

**Comment by kanav99** [comment]
I don't see any dev version here https://github.com/SciML/DiffEqFlux.jl/blob/gh-pages/versions.js , are there no tags? If they are not getting made automatically, then its an issue. Let me see

**Comment by ChrisRackauckas** [comment]
Yeah the tags aren't being made for some reason for the documentation. It's really weird.

**Comment by ChrisRackauckas** [comment]
Fixed.
