### ISSUE TITLE
How to calculate loss in a given time budget?

### ISSUE THREAD

**Issue by yifeima0421** [SciML/DiffEqFlux.jl#434]
Now i'd like to construct a Dataframe of loss values using different Optimizers 
with given processing time budget, which should looks like below.
But now my question is how to make this concrete?

│ Row │ Optimizer │ 1 min│ 2 mins │ 10 mins │ 20 mins  │
├───┼───────┼────┼─────┼─────┼──────┤
│   1    │ ADAM     │ 1.2     │ 0.5       │ 0.32      │ 0.12       │
│   2    │ BFGS      │ 1.3     │ 0.3       │ 0.26      │ 0.07       │
│   1    │ ADAMR   │ 1.3     │ 0.4      │ 0.23       │ 0.12       │

**Comment by ChrisRackauckas** [comment]
Answered in https://discourse.julialang.org/t/how-to-calculate-loss-in-a-given-time-budget/48369/4
