### ISSUE TITLE
Indexing issue caused by applychain

### ISSUE THREAD

**Issue by daniloefl** [SciML/DiffEqFlux.jl#436]
Dear DiffEqFlux developers,

I have tried using DiffEqFlux together with ArrayFire to take advantage of my GPU using OpenCL. Unfortunately, it does not quite work because `applychain` attempts to access elements outside of the array bounds in its last iteration. More precisely, `applychain` is defined as follows (in `src/fast_layers.jl`):

```
applychain(::Tuple{}, x, p) = x

applychain(fs::Tuple, x, p) = applychain(Base.tail(fs), first(fs)(x,p[1:paramlength(first(fs))]), p[(paramlength(first(fs))+1):end])
```

It recursively calls itself moving along the tuple of layers in the `FastChain` and shifting also the parameters array as it goes along. In the last call to itself, `paramlength(first(fs))+1` is bigger than the length of `p`, causing an exception.

This can be reproduced following the example in [1].

The fix is quite simple. The definition above could be replaced with:

```
applychain(::Tuple{}, x, p) = x

DiffEqFlux.applychain(fs::Tuple, x, p) = DiffEqFlux.applychain(Base.tail(fs), first(fs)(x,p[1:DiffEqFlux.paramlength(first(fs))]), length(fs) > 1 ? p[(DiffEqFlux.paramlength(first(fs))+1):end] : Tuple{}())
```

With this override, it all woks as expected. Although one could change ArrayFire to avoid an error in this case, it seems clear to me that `DiffEqFlux.jl` should not be trying to access a parameter beyond the array length in its last call.

Best regards,
Danilo

[1]
```
using ArrayFire
using Flux
using DiffEqFlux
using Zygote

hyper = FastChain(FastDense(1, 10, tanh), FastDense(10, 10, tanh), FastDense(10, 16, tanh))
p = initial_params(hyper)
x = rand(Float32, 1, 100)

af_p = AFArray(p)

hyper(x, af_p)
```

The error caused is:
```
julia> hyper(x, af_p)
ERROR: ArrayFire Error (202) : Invalid input argument
In function af_err af_index(void**, af_array, unsigned int, const af_seq*)
In file src/api/c/index.cpp:96
Invalid argument at index 3
Expected: indices_[i].begin <= indices_[i].end
 0# 0x00007F3805662D52 in /home/daniloefl/arrayfire/lib/libafopencl.so.3
 1# af_index_gen in /home/daniloefl/arrayfire/lib/libafopencl.so.3
 2# af_index_gen in /home/daniloefl/arrayfire/lib/libaf.so.3
 3# 0x00007F37E2DA5313
 4# 0x00007F37E2DAB45E
 5# 0x00007F37E2DAB648
 6# 0x00007F37E2DAB6ED
 7# 0x00007F37E2DAB707
 8# 0x00007F3839D7F25C in /home/daniloefl/Computer/julia/usr/bin/../lib/libjulia.so.1
 9# 0x00007F3839D7EE7A in /home/daniloefl/Computer/julia/usr/bin/../lib/libjulia.so.1
10# 0x00007F3839D7FB50 in /home/daniloefl/Computer/julia/usr/bin/../lib/libjulia.so.1
11# 0x00007F3839D80687 in /home/daniloefl/Computer/julia/usr/bin/../lib/libjulia.so.1
12# 0x00007F3839D9E0C1 in /home/daniloefl/Computer/julia/usr/bin/../lib/libjulia.so.1
13# 0x00007F3839D9E759 in /home/daniloefl/Computer/julia/usr/bin/../lib/libjulia.so.1
14# 0x00007
Stacktrace:
 [1] error(::String) at ./error.jl:33
 [2] _error(::UInt32, ::Bool) at /home/daniloefl/.julia/packages/ArrayFire/U0hth/src/util.jl:96
 [3] index_gen_1 at /home/daniloefl/.julia/packages/ArrayFire/U0hth/src/indexing.jl:91 [inlined]
 [4] getindex(::AFArray{Float32,1}, ::UnitRange{Int64}) at /home/daniloefl/.julia/packages/ArrayFire/U0hth/src/indexing.jl:66
 [5] applychain at /home/daniloefl/.julia/packages/DiffEqFlux/8UHw5/src/fast_layers.jl:20 [inlined] (repeats 3 times)
 [6] (::FastChain{Tuple{FastDense{typeof(tanh),DiffEqFlux.var"#initial_params#130"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}},FastDense{typeof(tanh),DiffEqFlux.var"#initial_params#130"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}},FastDense{typeof(tanh),DiffEqFlux.var"#initial_params#130"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}}}})(::Array{Float32,2}, ::AFArray{Float32,1}) at /home/daniloefl/.julia/packages/DiffEqFlux/8UHw5/src/fast_layers.jl:21
 [7] top-level scope at REPL[9]:1

```

**Comment by daniloefl** [comment]
NB: There is also another issue causing problems with Zygote's gradients if one uses `ArrayFire`, but this is an independent issue, which I have already filed (with a fix) here:

https://github.com/JuliaGPU/ArrayFire.jl/issues/268

**Comment by ChrisRackauckas** [comment]
>It recursively calls itself moving along the tuple of layers in the FastChain and shifting also the parameters array as it goes along. In the last call to itself, paramlength(first(fs))+1 is bigger than the length of p, causing an exception.

Yes, but then it's `N:end` where `N > length(array)`. That's a semantic that has a well-defined meaning in Julia:

```julia
julia> p = rand(100)
100-element Array{Float64,1}:
 0.2852505572063382
 0.9169936678252297
 0.8620565423826518
 0.166552680365611
 ⋮
 0.05960883198178646
 0.8229645210076109
 0.1491261429977191
 0.27502608607746537

julia> p[2:1]
Float64[]

julia> p[101:100]
Float64[]
```

Your fix introduces a type instability so it's not great. The real fix should be in ArrayFire to handle this case. That said, a similar hacky fix would be to do 

```julia
DiffEqFlux.applychain(fs::Tuple, x, p) = DiffEqFlux.applychain(Base.tail(fs), first(fs)(x,p[1:DiffEqFlux.paramlength(first(fs))]), length(fs) > 1 ? p[(DiffEqFlux.paramlength(first(fs))+1):end] : eltype(p)[])
```

so that it's type-stable, or to simply do the `if` outside of `applychain` and just stop the recursion when hitting the end of the array.

**Comment by daniloefl** [comment]
Hello @ChrisRackauckas ,

indeed I am not happy with the type change, now that you have mentioned it.
I wasn't aware that using indices above the array length like this was allowed in Julia. I will report it in ArrayFire.jl.

Best regards,
Danilo

**Comment by ChrisRackauckas** [comment]
Now one should just use Lux.jl since applychain/FastChain doesn't exist. And the true issue here was upstream in ArrayFire.
