### ISSUE TITLE
DiffEqFlux Failed to Train with Error "type BinaryHeap has no filed comparer"

### ISSUE THREAD

**Issue by ayaoyao214** [SciML/DiffEqFlux.jl#441]
Hi, I am learning the DiffEqFlux package and tried to implement the example given on the document https://julialang.org/blog/2019/01/fluxdiffeq/ 
Everything worked fine, however, the last step training broke with an error said: type BinaryHeap has no filed comparer. I am new to Julia and I cannot find any related issues that people have found out and fixed. Appreciate it if someone could help me out.

Here is the error:
![image](https://user-images.githubusercontent.com/45578607/97669875-07b0c380-1ac0-11eb-9ffc-37621af1120b.png)
Here is the relavent code:
![image](https://user-images.githubusercontent.com/45578607/97670016-54949a00-1ac0-11eb-9119-ada23c24cb5a.png)

Thanks a lot!!

**Comment by ChrisRackauckas** [comment]
Do `]add DataStructures@0.18` and figure out what package is keeping it back. It's a known issue where DataStructures did a breaking change which then doesn't play nicely with some package bounds out there. So the issues isn't necessarily DiffEqFlux, but some other package on your system is keeping DataStructures from having a compatible version and version weirdness with that exact transition then cause the issue. If you try and force the download of DataStructures v0.18 though, it'll tell you exactly which packages in your system are forcing it to stay back.

**Comment by ayaoyao214** [comment]
> Do `]add DataStructures@0.18` and figure out what package is keeping it back. It's a known issue where DataStructures did a breaking change which then doesn't play nicely with some package bounds out there. So the issues isn't necessarily DiffEqFlux, but some other package on your system is keeping DataStructures from having a compatible version and version weirdness with that exact transition then cause the issue. If you try and force the download of DataStructures v0.18 though, it'll tell you exactly which packages in your system are forcing it to stay back.

Hi Chris, thank you very much for the quick reply. Yes, this was the issue with the packages, I run ]add DataStructures@0.18 and the the information about the package conficts was listed, and I have romved some of the unused packages. It works now. Thanks again.

Btw, this is the currently versions I have on my nueral ODE training enviornment (I created a new environment for using DiffEqFlux to fixed the package conflict issue), for people who also has problem with using DiffEqFlux or training flux, these are the packages I need when training the simple example listed in the document.
![image](https://user-images.githubusercontent.com/45578607/98191367-036b2700-1f54-11eb-80ad-dc7b1278b8e7.png)
