### ISSUE TITLE
Using EnsembleDistributed() with Sciml_train?

### ISSUE THREAD

**Issue by smitch151** [SciML/DiffEqFlux.jl#452]
Hello, I'm trying to use sciml_train to update the initial position and variance of a SDE so that the final position of the SDE has a specific mean and variance. My code works just fine when I use EnsembleThreads() or EnsembleDistributed() to solve the Ensemble Problem. However, when I try to train the parameters, I find that sciml_train only works when using EnsembleThreads() and not EnsembleDistributed()? 

On an unrelated, but similar note, is it possible to reuse drawn SDE paths when running training iterations - i.e. draw 1000 paths and then train on different permutations of those 1000 paths before drawing another set of 1000 paths? 

```

### Packages
import Pkg; Pkg.build("DifferentialEquations")
import Pkg; Pkg.add("DifferentialEquations")
import Pkg; Pkg.add("IterTools")

using Distributed
using DifferentialEquations
using Flux
using DifferentialEquations.EnsembleAnalysis
using IterTools: ncycle
using Flux: @epochs
using DiffEqSensitivity
using Statistics
using DiffEqFlux

# Input parameters
T = 1.0f0
tspan = (0.0f0,T)
m=1.0
v=1.0
c=1.0
true_y0 = exp(T)*m + (exp(T)-1)*( sqrt(  2*v/(1-exp(-2*T)) )+1 )
true_Z = sqrt(2*v/(1-exp(-2*T)))
u0 = 7.5 # initial guess
Z = 1.6
p = [Z, u0]  |> gpu

function drift_nn!(du,u,p,t)
    du[1] = - u[1] - p[1] - c
end

function stoch_nn!(du,u,p,t)
    du[1] = p[1]
end

probSDE_nn = SDEProblem(drift_nn!,stoch_nn!,[p[2]],tspan,p)
ensemble_prob = gpu(EnsembleProblem(probSDE_nn))
@time sol = solve(ensemble_prob,EulerHeun(),saveat = T,EnsembleDistributed(), trajectories=1000,dt=0.05)

function loss_2(p)
    tmp_prob = remake(probSDE_nn,p=p,u0=[p[2]])
    ensemble_prob = gpu(EnsembleProblem(tmp_prob))
    sim = solve(ensemble_prob,EulerHeun(),saveat = T,EnsembleDistributed(),trajectories=1000, dt=0.05)
    arrsol = Array(sim)
    loss = (m - mean(arrsol,dims=3)[2])^2 + (v - var(arrsol,dims=3)[2])^2
end

p_init = deepcopy(p)


# train model on the same data num_cycle times
opt = ADAM(0.01)
@time res = DiffEqFlux.sciml_train(loss_2,p,opt, maxiters = 100)

```

The error I get is: Compiling Tuple{typeof(Base.maptwice),Base.var"#723#725"{Channel{Any},Array{Any,1},Distributed.var"#204#207"{CachingPool},Base.var"#716#721"{DiffEqBase.var"#360#361"{Base.Iterators.Pairs{Symbol,AbstractFloat,Tuple{Symbol,Symbol},NamedTuple{(:saveat, :dt),Tuple{Float32,Float64}}},EnsembleProblem{SDEProblem{Array{Float64,1},Tuple{Float32,Float32},true,Array{Float64,1},Nothing,SDEFunction{true,typeof(drift_nn!),typeof(stoch_nn!),LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(stoch_nn!),Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}},Nothing},typeof(DiffEqBase.DEFAULT_PROB_FUNC),typeof(DiffEqBase.DEFAULT_OUTPUT_FUNC),typeof(DiffEqBase.DEFAULT_REDUCTION),Nothing},EulerHeun}},Base.var"#722#724"{Channel{Any}}},Channel{Any},Array{Any,1},UnitRange{Int64}}: try/catch is not supported.

**Comment by ChrisRackauckas** [comment]
There was a missing adjoint to `pmap`. This "fixes" it:

```julia
using Distributed
using StochasticDiffEq
using Flux
using DiffEqBase.EnsembleAnalysis
using IterTools: ncycle
using Flux: @epochs
using DiffEqSensitivity
using Statistics
using DiffEqFlux

# Input parameters
T = 1.0f0
tspan = (0.0f0,T)
m=1.0
v=1.0
c=1.0
true_y0 = exp(T)*m + (exp(T)-1)*( sqrt(  2*v/(1-exp(-2*T)) )+1 )
true_Z = sqrt(2*v/(1-exp(-2*T)))
u0 = 7.5 # initial guess
Z = 1.6
p = [Z, u0]

function drift_nn!(du,u,p,t)
    du[1] = - u[1] - p[1] - c
end

function stoch_nn!(du,u,p,t)
    du[1] = p[1]
end

probSDE_nn = SDEProblem(drift_nn!,stoch_nn!,[p[2]],tspan,p)
ensemble_prob = gpu(EnsembleProblem(probSDE_nn))
@time sol = solve(ensemble_prob,EulerHeun(),saveat = T,EnsembleDistributed(), trajectories=1000,dt=0.05)

function loss_2(p)
    tmp_prob = remake(probSDE_nn,p=p,u0=[p[2]])
    ensemble_prob = gpu(EnsembleProblem(tmp_prob))
    sim = solve(ensemble_prob,EulerHeun(),saveat = T,EnsembleDistributed(),trajectories=1000, dt=0.05)
    arrsol = Array(sim)
    loss = (m - mean(arrsol,dims=3)[2])^2 + (v - var(arrsol,dims=3)[2])^2
end

p_init = deepcopy(p)

using Zygote

function ∇pmap(cx, f, wp, args...; kwargs...)
  ys_and_backs = pmap((args...) -> Zygote._pullback(cx, f, args...), wp, args...; kwargs...)
  if isempty(ys_and_backs)
    ys_and_backs, _ -> nothing
  else
    ys, backs = Zygote.unzip(ys_and_backs)
    ys, function (Δ)
      # Apply pullbacks in reverse order. Needed for correctness if `f` is stateful.
      Δf_and_args_zipped = pmap((f, δ) -> f(δ), wp, Zygote._tryreverse(pmap, backs, Δ)...)
      Δf_and_args = Zygote.unzip(Zygote._tryreverse(pmap, Δf_and_args_zipped))
      Δf = reduce(Zygote.accum, Δf_and_args[1])
      (Δf, nothing, Δf_and_args[2:end]...)
    end
  end
end

Zygote.@adjoint function Distributed.pmap(f, wp::Distributed.CachingPool, args::Union{AbstractArray,Tuple}...; kwargs...)
  ∇pmap(__context__, f, wp, args...; kwargs...)
end

# train model on the same data num_cycle times
opt = ADAM(0.01)
@time res = DiffEqFlux.sciml_train(loss_2,p,opt, maxiters = 100)
```

"fixes" as in, the adjoint stalls and I'm not quite sure why. This has a PR to Zygote to add the missing adjoint: https://github.com/FluxML/Zygote.jl/pull/845 . But I'll need to figure out why this occurs.

**Comment by smitch151** [comment]
I'm getting the following error when I try to run that code: 

"UndefVarError: _tryreverse not defined


Stacktrace:
 [1] (::var"#42#46"{CachingPool,Array{typeof(∂(λ)),1}})(::EnsembleSolution{Array{Float64,1},2,Array{Array{Array{Float64,1},1},1}}) at ./In[14]:55
 [2] #590#back at /home/ec2-user/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:55 [inlined]
 [3] #solve_batch#359 at /home/ec2-user/.julia/packages/DiffEqBase/V7P18/src/ensemble/basic_ensemble_solve.jl:172 [inlined]
 [4] (::typeof(∂(#solve_batch#359)))(::EnsembleSolution{Array{Float64,1},2,Array{Array{Array{Float64,1},1},1}}) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0 (repeats 2 times)
 [5] batch_function at /home/ec2-user/.julia/packages/DiffEqBase/V7P18/src/ensemble/basic_ensemble_solve.jl:108 [inlined]
 [6] (::typeof(∂(λ)))(::EnsembleSolution{Array{Float64,1},2,Array{Array{Array{Float64,1},1},1}}) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0
 [7] macro expansion at ./util.jl:234 [inlined]
 [8] #__solve#356 at /home/ec2-user/.julia/packages/DiffEqBase/V7P18/src/ensemble/basic_ensemble_solve.jl:112 [inlined]
 [9] (::typeof(∂(#__solve#356)))(::Array{Float64,3}) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0 (repeats 2 times)
 [10] #175 at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/lib/lib.jl:182 [inlined]
 [11] (::Zygote.var"#347#back#177"{Zygote.var"#175#176"{typeof(∂(__solve##kw)),Tuple{Tuple{Nothing,Nothing,Nothing},Tuple{Nothing,Nothing}}}})(::Array{Float64,3}) at /home/ec2-user/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [12] #solve#462 at /home/ec2-user/.julia/packages/DiffEqBase/V7P18/src/solve.jl:128 [inlined]
 [13] (::typeof(∂(#solve#462)))(::Array{Float64,3}) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0
 [14] (::Zygote.var"#175#176"{typeof(∂(#solve#462)),Tuple{Tuple{Nothing,Nothing,Nothing},Tuple{Nothing,Nothing}}})(::Array{Float64,3}) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/lib/lib.jl:182
 [15] #347#back at /home/ec2-user/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49 [inlined]
 [16] (::typeof(∂(solve##kw)))(::Array{Float64,3}) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0
 [17] loss_2 at ./In[14]:38 [inlined]
 [18] (::typeof(∂(loss_2)))(::Float64) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0
 [19] #175 at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/lib/lib.jl:182 [inlined]
 [20] (::Zygote.var"#347#back#177"{Zygote.var"#175#176"{typeof(∂(loss_2)),Tuple{Tuple{Nothing},Tuple{}}}})(::Float64) at /home/ec2-user/.julia/packages/ZygoteRules/6nssF/src/adjoint.jl:49
 [21] #33 at /home/ec2-user/.julia/packages/DiffEqFlux/FZMwP/src/train.jl:99 [inlined]
 [22] (::typeof(∂(λ)))(::Float64) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface2.jl:0
 [23] (::Zygote.var"#50#51"{Params,Zygote.Context,typeof(∂(λ))})(::Float64) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface.jl:177
 [24] gradient(::Function, ::Params) at /home/ec2-user/.julia/packages/Zygote/1GXzF/src/compiler/interface.jl:54
 [25] macro expansion at /home/ec2-user/.julia/packages/DiffEqFlux/FZMwP/src/train.jl:98 [inlined]
 [26] macro expansion at /home/ec2-user/.julia/packages/ProgressLogging/BBN0b/src/ProgressLogging.jl:328 [inlined]
 [27] (::DiffEqFlux.var"#32#37"{DiffEqFlux.var"#36#41",Int64,Bool,Bool,typeof(loss_2),Array{Float64,1},Params})() at /home/ec2-user/.julia/packages/DiffEqFlux/FZMwP/src/train.jl:43
 [28] with_logstate(::DiffEqFlux.var"#32#37"{DiffEqFlux.var"#36#41",Int64,Bool,Bool,typeof(loss_2),Array{Float64,1},Params}, ::Base.CoreLogging.LogState) at ./logging.jl:398
 [29] with_logger at ./logging.jl:505 [inlined]
 [30] maybe_with_logger(::DiffEqFlux.var"#32#37"{DiffEqFlux.var"#36#41",Int64,Bool,Bool,typeof(loss_2),Array{Float64,1},Params}, ::LoggingExtras.TeeLogger{Tuple{LoggingExtras.EarlyFilteredLogger{ConsoleProgressMonitor.ProgressLogger,DiffEqBase.var"#10#12"},LoggingExtras.EarlyFilteredLogger{Base.CoreLogging.SimpleLogger,DiffEqBase.var"#11#13"}}}) at /home/ec2-user/.julia/packages/DiffEqBase/V7P18/src/utils.jl:259
 [31] sciml_train(::Function, ::Array{Float64,1}, ::ADAM, ::Base.Iterators.Cycle{Tuple{DiffEqFlux.NullData}}; cb::Function, maxiters::Int64, progress::Bool, save_best::Bool) at /home/ec2-user/.julia/packages/DiffEqFlux/FZMwP/src/train.jl:42
 [32] macro expansion at ./util.jl:175 [inlined]
 [33] top-level scope at ./In[14]:69"

**Comment by ChrisRackauckas** [comment]
You have Zygote._tryreverse not just the direct function call?

**Comment by smitch151** [comment]
How do I check that?

**Comment by smitch151** [comment]
I tried updating Zygote and I still get the same error.

**Comment by ChrisRackauckas** [comment]
It's not going to work until the stall fixes, so we'll update the libraries when it's ready. It'll take a lot more work though given the issue I found.

**Comment by ChrisRackauckas** [comment]
Simpler adjoint:

```julia
using Zygote
Zygote.@adjoint function pmap(f, wp::Distributed.CachingPool, args...; kwargs...)
  ys_backs = pmap((x...) -> Zygote.pullback(f, x...), wp, args...; kwargs...)
  ys, backs = Zygote.unzip(ys_backs)
  ys, function (Δ)
    res = pmap((df,d) -> df(d), wp, backs, Δ; kwargs...)
    (nothing, nothing, Zygote.unzip(res)...)
  end
end
```

stalls like:

```julia
InterruptException:
try_yieldto(::typeof(Base.ensure_rescheduled)) at task.jl:656
wait at task.jl:713 [inlined]
wait(::Base.GenericCondition{ReentrantLock}) at condition.jl:106
take_buffered(::Channel{Any}) at channels.jl:387
take!(::Channel{Any}) at channels.jl:381
(::Zygote.var"#253#254"{Zygote.Context,Channel{Int64}})(::Nothing) at base.jl:56
#1953#back at adjoint.jl:49 [inlined]
wp_local_push! at workerpool.jl:68 [inlined]
push! at workerpool.jl:161 [inlined]
(::typeof(∂(push!)))(::Nothing) at interface2.jl:0
CachingPool at workerpool.jl:322 [inlined]
(::typeof(∂(CachingPool)))(::Nothing) at interface2.jl:0
#solve_batch#361 at basic_ensemble_solve.jl:168 [inlined]
(::typeof(∂(#solve_batch#361)))(::EnsembleSolution{Array{Float64,1},2,Array{Array{Array{Float64,1},1},1}}) at interface2.jl:0
solve_batch at basic_ensemble_solve.jl:168 [inlined]
(::typeof(∂(solve_batch##kw)))(::EnsembleSolution{Array{Float64,1},2,Array{Array{Array{Float64,1},1},1}}) at interface2.jl:0
macro expansion at timing.jl:233 [inlined]
#__solve#359 at basic_ensemble_solve.jl:108 [inlined]
(::typeof(∂(#__solve#359)))(::Array{Float64,3}) at interface2.jl:0
__solve at basic_ensemble_solve.jl:103 [inlined]
(::typeof(∂(__solve##kw)))(::Array{Float64,3}) at interface2.jl:0
#150 at lib.jl:191 [inlined]
(::Zygote.var"#1693#back#152"{Zygote.var"#150#151"{typeof(∂(__solve##kw)),Tuple{Tuple{Nothing,Nothing,Nothing},Tuple{Nothing,Nothing}}}})(::Array{Float64,3}) at adjoint.jl:49
#solve#458 at solve.jl:100 [inlined]
(::typeof(∂(#solve#458)))(::Array{Float64,3}) at interface2.jl:0
(::Zygote.var"#150#151"{typeof(∂(#solve#458)),Tuple{Tuple{Nothing,Nothing,Nothing},Tuple{Nothing,Nothing}}})(::Array{Float64,3}) at lib.jl:191
#1693#back at adjoint.jl:49 [inlined]
solve at solve.jl:97 [inlined]
(::typeof(∂(solve##kw)))(::Array{Float64,3}) at interface2.jl:0
loss_2 at test.jl:133 [inlined]
(::typeof(∂(loss_2)))(::Float64) at interface2.jl:0
#69 at train.jl:2 [inlined]
#150 at lib.jl:191 [inlined]
#1693#back at adjoint.jl:49 [inlined]
OptimizationFunction at basic_problems.jl:75 [inlined]
#150 at lib.jl:191 [inlined]
#1693#back at adjoint.jl:49 [inlined]
OptimizationFunction at basic_problems.jl:75 [inlined]
#150 at lib.jl:191 [inlined]
(::Zygote.var"#1693#back#152"{Zygote.var"#150#151"{typeof(∂(λ)),Tuple{Tuple{Nothing,Nothing},Int64}}})(::Float64) at adjoint.jl:49
#9 at solve.jl:98 [inlined]
(::typeof(∂(λ)))(::Float64) at interface2.jl:0
(::Zygote.var"#54#55"{Params,Zygote.Context,typeof(∂(λ))})(::Float64) at interface.jl:172
gradient(::Function, ::Params) at interface.jl:49
__solve(::OptimizationProblem{false,OptimizationFunction{false,GalacticOptim.AutoZygote,OptimizationFunction{true,GalacticOptim.AutoZygote,DiffEqFlux.var"#69#70"{typeof(loss_2)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},GalacticOptim.var"#147#157"{GalacticOptim.var"#146#156"{OptimizationFunction{true,GalacticOptim.AutoZygote,DiffEqFlux.var"#69#70"{typeof(loss_2)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing}},GalacticOptim.var"#150#160"{GalacticOptim.var"#146#156"{OptimizationFunction{true,GalacticOptim.AutoZygote,DiffEqFlux.var"#69#70"{typeof(loss_2)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing}},GalacticOptim.var"#155#165",Nothing,Nothing,Nothing},Array{Float64,1},DiffEqBase.NullParameters,Nothing,Nothing,Nothing,Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:maxiters,),Tuple{Int64}}}}, ::ADAM, ::Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}; cb::Function, maxiters::Int64, progress::Bool, save_best::Bool, kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at solve.jl:97
__solve at solve.jl:70 [inlined]
__solve at solve.jl:70 [inlined]
#solve#1 at solve.jl:11 [inlined]
(::DiffEqBase.var"#solve##kw")(::NamedTuple{(:maxiters,),Tuple{Int64}}, ::typeof(solve), ::OptimizationProblem{false,OptimizationFunction{false,GalacticOptim.AutoZygote,OptimizationFunction{true,GalacticOptim.AutoZygote,DiffEqFlux.var"#69#70"{typeof(loss_2)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},GalacticOptim.var"#147#157"{GalacticOptim.var"#146#156"{OptimizationFunction{true,GalacticOptim.AutoZygote,DiffEqFlux.var"#69#70"{typeof(loss_2)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing}},GalacticOptim.var"#150#160"{GalacticOptim.var"#146#156"{OptimizationFunction{true,GalacticOptim.AutoZygote,DiffEqFlux.var"#69#70"{typeof(loss_2)},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing}},GalacticOptim.var"#155#165",Nothing,Nothing,Nothing},Array{Float64,1},DiffEqBase.NullParameters,Nothing,Nothing,Nothing,Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:maxiters,),Tuple{Int64}}}}, ::ADAM) at solve.jl:11
sciml_train(::typeof(loss_2), ::Array{Float64,1}, ::ADAM, ::GalacticOptim.AutoZygote; kwargs::Base.Iterators.Pairs{Symbol,Int64,Tuple{Symbol},NamedTuple{(:maxiters,),Tuple{Int64}}}) at train.jl:5
(::DiffEqFlux.var"#sciml_train##kw")(::NamedTuple{(:maxiters,),Tuple{Int64}}, ::typ...
```

**Comment by ChrisRackauckas** [comment]
```julia
using Zygote
Zygote.@adjoint function pmap(f, wp::Distributed.CachingPool, args...; kwargs...)
  ys_backs = pmap((x...) -> Zygote.pullback(f, x...), wp, args...; kwargs...)
  ys, backs = Zygote.unzip(ys_backs)
  ys, function (Δ)
    res = pmap((df,d) -> df(d), wp, backs, Δ; kwargs...)
    (nothing, nothing, Zygote.unzip(res)...)
  end
end

Zygote.@nograd CachingPool
Zygote.@nograd workers
```

Adding this works 🎉 . I hope we can get Zygote merging this fix later today.

**Comment by smitch151** [comment]
The code runs for me when I use what you define there, but the parameters didn't update at all. 

``` 

using Distributed
using DifferentialEquations
using Flux
using DifferentialEquations.EnsembleAnalysis
using IterTools: ncycle
using Flux: @epochs
using DiffEqSensitivity
using Statistics
using DiffEqFlux
using DiffEqBase.EnsembleAnalysis

# Input parameters
T = 1.0f0
tspan = (0.0f0,T)
m=1.0
v=1.0
c=1.0
true_y0 = exp(T)*m + (exp(T)-1)*( sqrt(  2*v/(1-exp(-2*T)) )+1 )
true_Z = sqrt(2*v/(1-exp(-2*T)))
u0 = 10.0 # initial guess
NN = Chain(x -> x,
             Dense(1,5,relu),
             Dense(5,1)) |> gpu
p1,re = Flux.destructure(NN)
p = [p1; u0]  |> gpu
Z_init = re(p[1:length(p1)])([u0])[1]

function drift_nn!(du,u,p,t)
    du[1] = - u[1] - re(p[1:length(p1)])([p[end]])[1] - c
end

function stoch_nn!(du,u,p,t)
    du[1] = re(p[1:length(p1)])([p[end]])[1]
end

probSDE_nn = SDEProblem(drift_nn!,stoch_nn!,[p[end]],tspan,p)
ensemble_prob = gpu(EnsembleProblem(probSDE_nn))
@time sol = solve(ensemble_prob,EulerHeun(),saveat = T,EnsembleDistributed(), trajectories=1000,dt=0.05)

using Zygote
Zygote.@adjoint function pmap(f, wp::Distributed.CachingPool, args...; kwargs...)
  ys_backs = pmap((x...) -> Zygote.pullback(f, x...), wp, args...; kwargs...)
  ys, backs = Zygote.unzip(ys_backs)
  ys, function (Δ)
    res = pmap((df,d) -> df(d), wp, backs, Δ; kwargs...)
    (nothing, nothing, Zygote.unzip(res)...)
  end
end

Zygote.@nograd CachingPool
Zygote.@nograd workers

function loss_2(p)
    tmp_prob = remake(probSDE_nn,p=p,u0=[p[end]])
    ensemble_prob = gpu(EnsembleProblem(tmp_prob))
    sim = solve(ensemble_prob,EulerHeun(),saveat = T,EnsembleDistributed(),trajectories=1000, dt=0.05)
    arrsol = Array(sim)
    loss = (m - mean(arrsol,dims=3)[2])^2 + (v - var(arrsol,dims=3)[2])^2
end


opt = ADAM(0.1)
@time res = DiffEqFlux.sciml_train(loss_2,p,opt, maxiters = 3)
```

**Comment by ChrisRackauckas** [comment]
Yeah that one had a zero gradients issue. https://github.com/FluxML/Zygote.jl/pull/845 now fixes it. We'll just need to wait on the new release of Zygote.

**Comment by smitch151** [comment]
Awesome thank you very much!
