### ISSUE TITLE
implicit layers with neuralODEs ?

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DiffEqFlux.jl#478]
Came across application of implicit function theorem to neural-nets 
General idea is "need only jacobian at fixed point "

http://implicit-layers-tutorial.org/introduction/
https://github.com/locuslab/deq

Might be useful thing for DiffEqFlux ?

**Comment by ChrisRackauckas** [comment]
Already exists. Just use `SteadyStateProblem`.

**Comment by yewalenikhil65** [comment]
That would require data at steady-state or require availibility of ODEProblem ,right ?

Is the whole implicit-layers thing different than the way we normally approach in training neuralODEs as per DiffEqFlux docs. I am not much clear whether its better or not compared to our normal approach

**Comment by ChrisRackauckas** [comment]
It's literally the same. DEX is just a steady state problem, or a nonlinear solve `0 = f(u)` which is equivalent to finding `u' = 0` or a steady state of the ODE `u' = f(u)`. The adjoint on it is https://math.mit.edu/~stevenj/18.336/adjoint.pdf which is exactly the same as the DEX paper, just written 15 years earlier as equation (3).

**Comment by ChrisRackauckas** [comment]
We made a whole separate package around this: https://github.com/SciML/DeepEquilibriumNetworks.jl
