### ISSUE TITLE
FastChain-Compatible Layers without bias term

### ISSUE THREAD

**Issue by brendankeith** [SciML/DiffEqFlux.jl#480]
I would like to create a FastDense or StaticDense layer without a bias term. Something like this can be done in pytorch using a boolean flag (https://pytorch.org/docs/stable/generated/torch.nn.Linear.html#torch.nn.Linear) is this also possible with DiffEqFlux?

**Comment by ChrisRackauckas** [comment]
It's not implemented yet but it's not more than an hour's work. I think this is a good feature to point new devs to.

**Comment by aussetg** [comment]
#487
