### ISSUE TITLE
NeuralODE problem with component arrays not working

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DiffEqFlux.jl#497]
Hi , using following packages
```julia
  [b0b7db55] ComponentArrays v0.8.19
  [aae7a2af] DiffEqFlux v1.34.0
  [587475ba] Flux v0.11.6
  [429524aa] Optim v1.2.4

```
the example of NeuralODE using componentarrays mentioned here gives following error..

![image](https://user-images.githubusercontent.com/26343789/109697032-bf132f00-7bb3-11eb-905a-6620f3dde1be.png)

**Comment by ChrisRackauckas** [comment]
This should be an issue with ComponentArrays?

**Comment by yewalenikhil65** [comment]
> This should be an issue with ComponentArrays?

 yes i guess..
i raised the issue here since I first found it at https://diffeqflux.sciml.ai/stable/Flux/#Using-ComponentArrays-for-neural-network-layers-1
As i was unsure what is real issue, i raised issue at both repos.. diffeqflux and componentarrays

**Comment by yewalenikhil65** [comment]
fixed by `ComponentArrays` maintainers with their new update yesterday
