### ISSUE TITLE
MethodError: no method matching length(::Nothing)

### ISSUE THREAD

**Issue by praveenyati10** [SciML/DiffEqFlux.jl#498]
Was trying to predict parameters for duffing equation using BlackBoxOptim. It worked in julia 1.5.1 but not working in julia 1.5.3
and throwing error-**MethodError: no method matching `length(::Nothing)**`

```
using BlackBoxOptim

using Optim

function loss(p)
        tmp_prob=remake(prob,p=p)
        tmp_sol=solve(tmp_prob,MethodOfSteps(Tsit5()),p=p,saveat=0.01)
        sum(abs2,Array(tmp_sol)-dataset),tmp_sol
end



pinit=[1.0,1.0,0.5]
res3=DiffEqFlux.sciml_train(loss,pinit,DiffEqFlux.BBO(),lower_bounds=0.0ones(4),upper_bounds=4.0ones(4))

```

**Comment by ChrisRackauckas** [comment]
The fix is in https://github.com/SciML/DiffEqFlux.jl/pull/499 and should merge tomorrow.
