### ISSUE TITLE
Make docs nicer

### ISSUE THREAD

**Issue by drozzy** [SciML/DiffEqFlux.jl#504]
I think the docs should have these sections:

1. Neural networks can be defined where the "activations" are nonlinear functions described by differential equations
2. Neural networks can be defined where some layers are ODE solves
3. ODEs can be defined where some terms are neural networks
4. Cost functions on ODEs can define neural networks

**Comment by ChrisRackauckas** [comment]
What's the proposal for getting there? I don't think 4 sections will make too much sense, because then it would mix Bayesian, SDEs, etc. Also, (4) isn't in this library but NeuralPDE.jl now.

**Comment by ChrisRackauckas** [comment]
A documenter.jl issue is that we only get 1 depth of the headers.

**Comment by drozzy** [comment]
Well, I think we could call it "main themes" or something, basically an overview of capabilities of the package.
<img width="305" alt="Screen Shot 2021-03-11 at 9 18 30 AM" src="https://user-images.githubusercontent.com/140710/110800966-bfae6400-824a-11eb-9b5a-f50e756013ef.png">

So there is a clear path of common use cases and everything else can go under advanced section.

**Comment by drozzy** [comment]
For example the section headers "Basic Parameter tutorials" vs "Neural ODE and SDE Tutorials" don't really add much imo.
I still have to look through both..

**Comment by drozzy** [comment]
Even organization along these lines would be nice (I don't mind repetition of the same stuff over and over, since each example could be self-contained thing):
<img width="849" alt="Screen Shot 2021-03-11 at 9 23 01 AM" src="https://user-images.githubusercontent.com/140710/110801570-6135b580-824b-11eb-9dc4-4d7fa5578b7b.png">

**Comment by drozzy** [comment]
For example, if I'm looking for a PINN to fix some diff equation's parameters, I really want to see "ODEs can be defined where some terms are neural networks" (if I'm not mistaken), but as it is right now I have to look at both:
<img width="267" alt="Screen Shot 2021-03-11 at 9 25 54 AM" src="https://user-images.githubusercontent.com/140710/110802016-ca1d2d80-824b-11eb-81d4-cddaece44aa4.png">

**Comment by drozzy** [comment]
I guess the issue is that the docs say "how something is done" instead of "what you want to achieve" maybe?

**Comment by ChrisRackauckas** [comment]
Do you have a better suggestion than "not neural tutorials"? Or do you think we should split it up into "ODE Tutorials" and "SDE Tutorials", and "DDE Tutorials", and "PDE Tutorials"? 

- ODE Tutorials
- SDE Tutorials
- DDE Tutorials
- PDE Tutorials
- Hybrid and Jump Tutorials
- FAQ, Tips, and Tricks
- Bayesian Estimation Tutorials
- Optimal and Model Predictive Control Tutorials
- UDE Tutorials
- Layer APIs
- Manual and APIs
- Benchmarks

?

**Comment by drozzy** [comment]
Yea, I was looking for something like "PDE Tutorials" section, but I couldn't find it.

**Comment by drozzy** [comment]
Someone posted this link on another issue I think it might be helpful:
https://documentation.divio.com/

**Comment by ChrisRackauckas** [comment]
Fixed to the format discussed. Check it out. For more follow-up, make a PR as I think some of the high level discussion won't be translatable to action.

**Comment by drozzy** [comment]
Very nice thanks!
