### ISSUE TITLE
Is there any difference in neuralODE and ODENet?

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/DiffEqFlux.jl#510]
https://arxiv.org/pdf/2005.04849.pdf   
This looks like what we are attemting to do at https://github.com/SciML/DataDrivenDiffEq.jl/issues/54
They claim `intrepretability` like SINDy and yet the framework looks like neuralODE
Am i correct ?

**Comment by ChrisRackauckas** [comment]
Yeah, not much else to it.
