### ISSUE TITLE
sciml_train summary is gone?

### ISSUE THREAD

**Issue by seadra** [SciML/DiffEqFlux.jl#513]
sciml_train used to print an informative summary at the end, like this
```
 * Status: failure

 * Candidate solution
    Final objective value:

 * Found with
    Algorithm:     BFGS

 * Convergence measures
...

 * Work counters
    Seconds run:   138  (vs limit Inf)
    Iterations:    78
    f(x) calls:    100
    ∇f(x) calls:   100
```

but it is gone in the current release. Is it behind an option, or is it completely gone?

**Comment by ChrisRackauckas** [comment]
That would be an issue for GalacticOptim and the OptimizationSolution.

**Comment by seadra** [comment]
But I'm using DiffEqFlux.sciml_train. Should I nonetheless open this in GalacticOptim?

**Comment by ChrisRackauckas** [comment]
It's all GalacticOptim under the hood now.

**Comment by seadra** [comment]
I see, thanks!
