### ISSUE TITLE
Possible Indexing error in multiple_shoot

### ISSUE THREAD

**Issue by adrhill** [SciML/DiffEqFlux.jl#522]
When calling `multiple_shoot` with `grp_size=2`, the following line is called:
https://github.com/SciML/DiffEqFlux.jl/blob/ee4937f33148dfeb7b71914763b9b8b86c4dc094/src/multiple_shooting.jl#L50

Which looks equal to calling the function with `grp_size=1`:
https://github.com/SciML/DiffEqFlux.jl/blob/ee4937f33148dfeb7b71914763b9b8b86c4dc094/src/multiple_shooting.jl#L35-L37

I also feel like the three cases (`grp_size==datasize`, `grp_size==1`, else) are not really necessary, as they all perform the same calculation. 

___ 

On another note, `test/multiple_shoot.jl` doesn't seem to be included in `runtests.jl` yet.

**Comment by ChrisRackauckas** [comment]
Yes, those cases probably aren't necessary.

**Comment by yewalenikhil65** [comment]
Copy pasting the code now also seems to throw error on Tsit5 not defined ?
I am sure it was working fine a couple of weeks back though
![image](https://user-images.githubusercontent.com/26343789/114272154-97c14480-9a32-11eb-8fcb-afd75c7354bf.png)

**Comment by adrhill** [comment]
I think PR #521 fixes this.

**Comment by yewalenikhil65** [comment]
> I think PR #521 fixes this.

Awesome!

**Comment by adrhill** [comment]
This was closed by #535.
