### ISSUE TITLE
Regarding Neural ODE Documentation

### ISSUE THREAD

**Issue by QiyaoWei** [SciML/DiffEqFlux.jl#538]
Hi all,

I was looking at this documentation (https://diffeqflux.sciml.ai/dev/examples/neural_ode_sciml/#Usage-without-the-layer) about not using the NeuralODE wrapper, and noticed there might be a slight misprint. Specifically, the code collection at the very bottom after the line "In total, the 'from-scratch' form looks like" doesn't look right. Isn't this code supposed to demonstrate how to bypass the NeuralODE wrapper? I don't think it should be an exact replica of the section "copy-pasteable code" right?

**Comment by ChrisRackauckas** [comment]
Yes, thanks for the issue. Vaibhav's fix should be what you're looking for.
