### ISSUE TITLE
FFJORD for flexible batched data

### ISSUE THREAD

**Issue by John-Boik** [SciML/DiffEqFlux.jl#540]
I would like to call FFJORD using batched data, and to do so in a flexible way such that each batch can be created on the fly (as opposed to calling FFJORD with a data iterator). This issue might be related to the closed issue [FFJORD for batched data #342](https://github.com/SciML/DiffEqFlux.jl/issues/342), but if so, I am not seeing a solution.

The easiest way to explain might be to use a script from the FFJORD test file as a starting point. The following code works just fine:

```
import OrdinaryDiffEq
import Flux
import DiffEqFlux
import GalacticOptim
import Distributions
import Distances
import Zygote
import DistributionsAD
import LinearAlgebra
import Random

Random.seed!(1999)

##callback to be used by all tests
function cb(p,l)
    @show l
    false
end


nn = Flux.Chain(Flux.Dense(1, 1, tanh))
data_train = Float32.(rand(Distributions.Beta(7,7), 1, 100))
tspan = (0.0f0, 1.0f0)
cnf_test = DiffEqFlux.FFJORD(nn, tspan, OrdinaryDiffEq.Tsit5())

function loss_adjoint(θ) 
    logpx = cnf_test(data_train, θ; monte_carlo=false)[1]
    loss = -Distances.mean(logpx)
end

optfunc = GalacticOptim.OptimizationFunction((x, p) -> loss_adjoint(x), GalacticOptim.AutoZygote())
optprob = GalacticOptim.OptimizationProblem(optfunc, cnf_test.p)  
res = GalacticOptim.solve(optprob, Flux.ADAM(0.1), cb=cb, maxiters = 100)
```
But I wish to call FFJORD using flexible batch data. For example, building on the above, I would like to call FFJORD inside a for loop, where in each iteration I create a new data sample, `data_train`. Then the solve in each iteration has maxiter=1.

Perhaps there is a way to do so using `GalacticOptim.solve`, but I can't figure out how. The following does not work:

```
import OrdinaryDiffEq
import Flux
import DiffEqFlux
import GalacticOptim
import Distributions
import Distances
import Zygote
import DistributionsAD
import LinearAlgebra
import Random

using Infiltrator
using Formatting
using Revise


Random.seed!(1999)

##callback to be used by all tests
function cb(p,l)
    @show l
    false
end

nn = Flux.Chain(Flux.Dense(1, 1, tanh))
tspan = (0.0f0, 1.0f0)
cnf_test = DiffEqFlux.FFJORD(nn, tspan, OrdinaryDiffEq.Tsit5())

function loss_adjoint(θ, data_train)  
    logpx = cnf_test(data_train, θ; monte_carlo=false)[1]
    loss = -Distances.mean(logpx)
end

optfunc = GalacticOptim.OptimizationFunction((x,p) -> loss_adjoint(x,p), GalacticOptim.AutoZygote())
data = Float32.(rand(Distributions.Beta(7,7), 1, 100))  # needed to initialize data for the next line
optprob = GalacticOptim.OptimizationProblem(optfunc, 0.01f0 .* cnf_test.p, data)

for ii in 1:10
    local data_train, res 
    data_train = Float32.(rand(Distributions.Beta(7,7), 1, 100))
    res = GalacticOptim.solve(optprob, Flux.ADAM(0.1), data=data_train, cb=cb, maxiters = 1) 
end
```
The `loss_adjoint` function is called with the same data values each iteration and the loss never changes. I am probably passing the new `data_train` in each iteration the wrong way. Is there a right way to do this? 

Another approach might be to use `Zygote.gradient` rather than `GalacticOptim.solve`. But if so, I don't know how to do that without raising errors in FFJORD. The following does not work:

```
import OrdinaryDiffEq
import Flux
import DiffEqFlux
import GalacticOptim
import Distributions
import Distances
import Zygote
import DistributionsAD
import LinearAlgebra
import Random

using Infiltrator
using Formatting
using Revise


Random.seed!(1999)

##callback to be used by all tests
function cb(p,l)
    @show l
    false
end

nn = Flux.Chain(Flux.Dense(1, 1, tanh))
tspan = (0.0f0, 1.0f0)
cnf_test = DiffEqFlux.FFJORD(nn, tspan, OrdinaryDiffEq.Tsit5())

function loss_adjoint(θ, data)
    logpx = cnf_test(data, θ; monte_carlo=false)[1]
    loss = -Distances.mean(logpx)
end

opt = Flux.Optimise.ADAM(0.1)
params = Zygote.Params(Flux.params(nn))

for ii in 1:10
    local data_train
    data_train = Float32.(rand(Distributions.Beta(7,7), 1, 100))
    
    gradients = Zygote.gradient(params) do
        train_loss = loss_adjoint(params, data_train)
        @show train_loss
        return train_loss
    end
    
    Flux.update!(opt, params, gradients) 
end
```
The above code raises the error `ERROR: LoadError: MethodError: Cannot `convert` an object of type Float32 to an object of type Matrix{Float32}` in the function call to FFJORD, at the lines
```
_z = Zygote.@ignore similar(x, 1, size(x, 2))
Zygote.@ignore fill!(_z, 0.0f0)
```
I assume that FFJORD is expecting a matrix for θ, and I am passing a Params object.

Is there some way to call FFJORD with (flexible) batch data?

**Comment by ChrisRackauckas** [comment]
Looks like a bug and needs an interface fix.

**Comment by John-Boik** [comment]
I might try to hack a solution unless someone is planning to tackle this issue in the near future. If I do, I'm leaning toward the approach above that calls `gradients = Zygote.gradient(params) do ...`, as opposed to calling `GalacticOptim.solve`.  Does anyone have suggestions, or advice to use a different approach?

**Comment by ChrisRackauckas** [comment]
I'm not sure, I haven't used data iterators too much. Maybe @Vaibhavdixit02 has an opinion

**Comment by Vaibhavdixit02** [comment]
This works for me can you confirm this is what you are attempting @John-Boik?

```
import OrdinaryDiffEq
import Flux
import DiffEqFlux
import GalacticOptim
import Distributions
import Distances
import Zygote
import DistributionsAD
import LinearAlgebra
import Random

using Infiltrator
using Formatting
using Revise


Random.seed!(1999)

##callback to be used by all tests
function _cb(p,l)
    @show l
    false
end

nn = Flux.Chain(Flux.Dense(1, 1, tanh))
tspan = (0.0f0, 1.0f0)
cnf_test = DiffEqFlux.FFJORD(nn, tspan, OrdinaryDiffEq.Tsit5())

function loss_adjoint(θ, y, x)
    logpx = first.(cnf_test(y, θ; monte_carlo=false))
    loss = -Distances.mean(logpx)
end

optfunc = GalacticOptim.OptimizationFunction((θ,p,y,x) -> loss_adjoint(θ, y, x), GalacticOptim.AutoZygote())
optprob = GalacticOptim.OptimizationProblem(optfunc, 0.01f0 .* cnf_test.p)

data_ = Float32.(fill(rand(Distributions.Beta(7,7)), 1, 100))
data = Flux.Data.DataLoader((data_, 1:100))  # needed to initialize data for the next line

GalacticOptim.solve(optprob, Flux.ADAM(0.1), data, cb=_cb)

data = Flux.Data.DataLoader((Float32.(rand(Distributions.Beta(7,7), 1, 1000)), repeat(collect(1:100), 10)), batchsize = 100) 
GalacticOptim.solve(optprob, Flux.ADAM(0.1), data, cb=_cb)
```

**Comment by John-Boik** [comment]
Thanks @Vaibhavdixit02. 
Unfortunately, while this code runs correctly, it does not address the question I had in mind. I would like to call FFJORD using batched data, but in a flexible way such that each data batch can be created on the fly (as opposed to using a data iterator). For example, rather than using DataLoader as you do, I would like to do something like:
```
    setup model
    for ii in 1:Nbatches
         make data batch ii on the fly, perhaps through some complicated process
         train model using data batch ii and adjust parameters based on error gradient
    end
```
That is why I am leaning toward using `Zygote.gradient` directly rather than using `GalacticOptim.solve`. 
Any ideas on this?

**Comment by John-Boik** [comment]
I'd like to continue the optimization, so each training batch reduces the error.

**Comment by Vaibhavdixit02** [comment]
You just want this loop then

```
optfunc = GalacticOptim.OptimizationFunction((θ,p,y,x) -> loss_adjoint(θ, y, x), GalacticOptim.AutoZygote())

_p = 0.01f0 .* cnf_test.p

for i in 1:10
    optprob = GalacticOptim.OptimizationProblem(optfunc, _p)
    data_ = Float32.(fill(rand(Distributions.Beta(7,7)), 1, 100))
    data = Flux.Data.DataLoader((data_, 1:100))  # needed to initialize data for the next line
    res = GalacticOptim.solve(optprob, Flux.ADAM(0.1), data, cb=_cb) #single batch of length 100
    _p = res.u
end
``

**Comment by John-Boik** [comment]
That's just what I was after, and appears to work perfectly. Thanks @Vaibhavdixit02! Something like this might be a good example in the documentation, as I suspect I'm not the only person who wishes to create data batches on the fly (rather than using a data iterator).
