### ISSUE TITLE
Mass matrix example requires mass to always equal 1

### ISSUE THREAD

**Issue by ctessum** [SciML/DiffEqFlux.jl#553]
Hello, 

I'm not sure if this is a feature request, or perhaps a documentation request, or maybe me just not understanding how things work. In the test and example for the neural ode with mass matrix, my understanding is that the total mass in the system is [hard-coded to equal 1](https://github.com/SciML/DiffEqFlux.jl/blob/7f2a25d0f3f86161127edd5e3f36bf19c8b5c50d/test/neural_ode_mm.jl#L8). So the example only works when the sum of uo equals 1; if the initial conditions were different, you would have to hard-code in a different total mass.

If I am understanding this correctly, is there a way to use a mass matrix without specifying what the mass is ahead of time, so it would work correctly no matter what the initial conditions are?

cc @xiaoky97

**Comment by ChrisRackauckas** [comment]
The adjoint with respect to the mass matrix isn't implemented, though you could still calculate it if you did direct differentiation of the solver (i.e. ReverseDiff + `sensealg=DiffEqBase.ADPassThrough()`). As such, the mass matrix is assumed to be a known constant. You could of course divide the right hand side by `m_i`, i.e. `f_i(u)/m_i`, and then `m_i` would be a normal parameter to train. That would allow for non-1's in the semi-explicit form. For more complex structures, normally you'd know the structure but maybe not the scaling factor, like if your mass matrix comes from an FEM discretization with an unknown diffusion then the same `m_i` trick would work there.

Does that cover your cases?

**Comment by ctessum** [comment]
Thanks! I think my issue may be simpler than that. I doesn't directly involve the adjoint. Put another way, the issue is that `du[3] =  y₁ + y₂ + y₃ - 1` only works when `u₀ = [1.0, 0, 0]` or more generally `sum(u₀) == 1`. It seems like it would be useful for it to also work when `u₀ = [2.0, 0, 0]` without having to rewrite the source code.

I'm guessing that we can't just do `du[3] =  y₁ + y₂ + y₃ - sum(u)`, because that wouldn't work correctly with the mass matrix.

I guess one way could be to do something this:

``` julia
function f(du,u,p,t)
    y₁,y₂,y₃,ytotal = u
    k₁,k₂,k₃ = p
    du[1] = -k₁*y₁ + k₃*y₂*y₃
    du[2] =  k₁*y₁ - k₃*y₂*y₃ - k₂*y₂^2
    du[3] =  y₁ + y₂ + y₃ - ytotal
    du[4] = 0 # because ytotal doesn't change
    nothing
end
```
but that requires the redundant state variable `ytotal` (which is just `sum(u)`), which seems inelegant.

It seems like a more intuitive and general way to express a conservation equation would be `sum(du) == 0` rather than `sum(u) == 1`, but I'm not sure how to make that work in the context of a mass matrix.

Does that make it any clearer? It's very possible that there's an apparently obvious solution that I'm just missing here.

**Comment by ctessum** [comment]
Or maybe should it be `du[3] =  y₁ + du[1] + y₂ + du[2] + y₃ - sum(u)` or something like that?

**Comment by ChrisRackauckas** [comment]
That other value can just be a parameter.

**Comment by ctessum** [comment]
Thanks! Yes, that will work in this case where the mass is always the same. But for example if I have a bunch of data that represents trajectories of a system when given different initial conditions, and each initial condition has a different total mass, then I can't set the total mass as a parameter, because it changes depending on what the initial conditions are. I could include the separately calculated total mass for each initial condition as a part of `u`, but I thought there might be a way to avoid doing that. It's sounds like there maybe isn't one?

**Comment by ChrisRackauckas** [comment]
You can use a functor to enclose the constant into `f`:

```
struct myf{T}
  m_i::T
end

function (f::myf)(du,u,p,t)
  du[1] = (...)/f.m_i
end

f = myf(1.0) # this is the function with /1.0
f = myf(2.0) # this is the function with /2.0

**Comment by ctessum** [comment]
Thanks! That's closer, but still not quite what I'm looking for. I'll close this for now, because we found a different way to achieve the underlying goal. I appreciate your help!
