### ISSUE TITLE
Unstable `FastDense` `hash` and comparison.

### ISSUE THREAD

**Issue by korsbo** [SciML/DiffEqFlux.jl#555]
I was trying to store my models in a data structure and use them for filtering, etc., but I found it tricky to compare my model objects. Storing a model/NN (or a hash thereof) alongside its fitted parameters could make it easier to ensure that one does not apply an old set of parameters to an updated model/NN. But seemingly identical `FastDense` objects do not generate identical hashes or compare well.

```julia
using DiffEqFlux
using Flux
FastDense(2,3) == FastDense(2,3)
FastDense(2,3; initW=Flux.zeros) == FastDense(2,3; initW=Flux.zeros)
FastDense(2,3; initW=Flux.zeros, initb=Flux.zeros) == FastDense(2,3; initW=Flux.zeros, initb=Flux.zeros)
hash(FastDense(2,3; initW=Flux.zeros, initb=Flux.zeros)) == hash(FastDense(2,3; initW=Flux.zeros, initb=Flux.zeros))
```

all returns `false`. The first one does not surprise me since you store a vector of random numbers inside the `FastDense` object. The rest of them, however.

**Comment by ChrisRackauckas** [comment]
So you're just looking for `==` and `hash` overloads?

**Comment by ChrisRackauckas** [comment]
FastDense is gone.
