### ISSUE TITLE
sample code running slow on Atom

### ISSUE THREAD

**Issue by ChironJC** [SciML/DiffEqFlux.jl#560]
I am using the atom juno IDE to run the sample code. The code is provided by DiffEqFlux.jl document. 

Code cannot run as fast as it is shown in README.md gif though I think we are using the same example. It takes me several minutes to run an epoch. Does anyone have ideas about why this happens?

**Comment by ChrisRackauckas** [comment]
Are you using Julia v1.6 and the latest package version?
