### ISSUE TITLE
Typo in minibatching example

### ISSUE THREAD

**Issue by bkuwahara** [SciML/DiffEqFlux.jl#570]
I believe there's a typo in the minibatching example (https://diffeqflux.sciml.ai/stable/examples/minibatch/). The line
`train_loader = Flux.Data.DataLoader(ode_data, t, batchsize = k)` gives an error `MethodError: no method matching Flux.Data.DataLoader(::Matrix{Float32}, ::StepRangeLen{Float32, Float64, Float64}; batchsize=10)`. Changing it to `train_loader = Flux.Data.DataLoader((ode_data, t), batchsize = k)` gets the desired result (I think). 

I say "I think" because the output of the loop which displays the contents of `data_loader` looks correct, but then the training doesn't converge. The minimum loss I get is about 20 and it doesn't generalize at all.

**Comment by ChrisRackauckas** [comment]
@avik-pal ?

**Comment by avik-pal** [comment]
>  The minimum loss I get is about 20 and it doesn't generalize at all.

It reaches 0.96 for me after the dataloader fix you mentioned
