### ISSUE TITLE
`multiple_shoot` for `EnsembleProblem`

### ISSUE THREAD

**Issue by vboussange** [SciML/DiffEqFlux.jl#601]
Hey guys, 
I need to do multiple shooting with an `EnsembleProblem`.
Does it make sense for you to overload `multiple_shoot` for `EnsembleProblem`? 
I am happy to propose a PR 😊

**Comment by Vaibhavdixit02** [comment]
I think it would be useful but not sure what that might look like, since it could probably work in a couple of different ways, do you have any use case for it? Feel free to open the PR and we can discuss it better there

**Comment by vboussange** [comment]
Sure, I will open a PR any time soon
