### ISSUE TITLE
zeros32 not defined

### ISSUE THREAD

**Issue by Dale-Black** [SciML/DiffEqFlux.jl#606]
Just wanted to mention this here in case it is useful. I ran into a problem using the newest version of Flux (v0.12.6) and DiffEqFlux (v1.43.0) where it errors. I think it's related to [this PR](https://github.com/FluxML/Flux.jl/pull/1661) but I am not positive

```julia
UndefVarError: zeros32 not defined

DiffEqFlux.FastDense(::Int64, ::Int64, ::Function)@fast_layers.jl:45
top-level scope@Local: 4
```

**Comment by Vaibhavdixit02** [comment]
I think you are not using the current version if you saw that, did you restart the Julia session after updating to newer versions?

**Comment by Dale-Black** [comment]
I might be missing something but I just reinstalled those two packages to the newest version after restarting Julia and I am still getting the same error above

```julia
begin
	let
		using Pkg
		Pkg.activate(mktempdir())
		Pkg.Registry.update()
		Pkg.add([
				Pkg.PackageSpec(name="Flux", version="0.12.6")
				Pkg.PackageSpec(name="DiffEqFlux", version="1.43.0")
				])
		Pkg.add([
				"PlutoUI"
				"NeuralPDE"
				"Quadrature"
				"Cubature"
				"Cuba"
				"ModelingToolkit"
				"GalacticOptim"
				"Optim"
				"Plots"
				"DelimitedFiles"
				"QuasiMonteCarlo"
				])
	end
	
	using PlutoUI 
	using NeuralPDE
	using Quadrature, Cubature, Cuba
	using Flux, ModelingToolkit, GalacticOptim, Optim, DiffEqFlux
	using Plots
	using DelimitedFiles
	using QuasiMonteCarlo
end
```

```julia
begin
	## NEURAL NETWORK
    nrns = 16   #neuron number
    chain = FastChain(
		FastDense(3,nrns,Flux.σ),
		FastDense(nrns,nrns,Flux.σ),
		FastDense(nrns,1)
		)   #Neural network from Flux library
    initθ = Float64.(DiffEqFlux.initial_params(chain))
end
```

```julia

UndefVarError: zeros32 not defined

DiffEqFlux.FastDense(::Int64, ::Int64, ::Function)@fast_layers.jl:45
top-level scope@Local: 4
```

**Comment by ChrisRackauckas** [comment]
`zeros32` definitely exists in Flux v0.12.6:

https://github.com/FluxML/Flux.jl/blob/v0.12.6/src/layers/recurrent.jl#L80

**Comment by Dale-Black** [comment]
Yeah, it looks like you are right and it works. I am not sure what I was doing wrong in the beginning. Whoops!
