### ISSUE TITLE
Suggestion: Apply to infection prediction

### ISSUE THREAD

**Issue by EngrStudent** [SciML/DiffEqFlux.jl#607]
My kids currently (~ww33'21) have hand-foot-mouth and I was looking at the papers and articles on the subject to try and get vague sense of how long they will be infectious.  

In the exploration I saw this:
https://www.nature.com/articles/s41598-020-68840-3

It is in Nature, a relatively credible journal, and from middle of last year, so relatively relatively recent. 

The best they had was a deep recurrent convolutional residual (homebrew) something.  
And the basic SIR models are differential equations, and they could do a job here.

I do not understand the neural+ODE and the SEIR epidemiology well enough to do a decent job, but I strongly suspect that a non-shallow Neural ODE based on SEIR models might substantially outperform the homebrew substantially.  If they could compare favorably against relatively recent, relatively credible approaches that are being shared, then I think they should be considered.

If credible neural+ODE approaches for SEIR models have been articulated, could you point me to them.  If not, then you might consider making the approach known to the corresponding author, and considering engaging in follow-up there.

Regards,
Michael Munroe (engineering student)

**Comment by ChrisRackauckas** [comment]
https://www.nature.com/articles/s41598-023-37118-9
https://www.cell.com/patterns/pdf/S2666-3899(21)00034-9.pdf
https://www.osti.gov/biblio/1888443
https://spj.science.org/doi/full/10.34133/2021/9798302?adobe_mc=MCMID%3D22000014905405683995335849378418609464%7CMCORGID%3D242B6472541199F70A4C98A6%2540AdobeOrg%7CTS%3D1674864000
https://www.cell.com/patterns/pdf/S2666-3899(20)30193-8.pdf

**Comment by EngrStudent** [comment]
Very nice! Thank you.
