### ISSUE TITLE
type HMCKernel has no field integrator

### ISSUE THREAD

**Issue by tortijazz** [SciML/DiffEqFlux.jl#618]
Hi everybody,

I'm trying to run this code on Julia 1.6.2 version:

```
using DiffEqFlux, DifferentialEquations, Plots, AdvancedHMC, MCMCChains
using JLD, StatsPlots

u0 = [2.0; 0.0]
datasize = 40
tspan = (0.0, 1)
tsteps = range(tspan[1], tspan[2], length = datasize)

function trueODEfunc(du, u, p, t)
    true_A = [-0.1 2.0; -2.0 -0.1]
    du .= ((u.^3)'true_A)'
end

prob_trueode = ODEProblem(trueODEfunc, u0, tspan)
ode_data = Array(solve(prob_trueode, Tsit5(), saveat = tsteps))


dudt2 = FastChain((x, p) -> x.^3,
                  FastDense(2, 50, tanh),
                  FastDense(50, 2))
prob_neuralode = NeuralODE(dudt2, tspan, Tsit5(), saveat = tsteps)

function predict_neuralode(p)
    Array(prob_neuralode(u0, p))
end

function loss_neuralode(p)
    pred = predict_neuralode(p)
    loss = sum(abs2, ode_data .- pred)
    return loss, pred
end

l(θ) = -sum(abs2, ode_data .- predict_neuralode(θ)) - sum(θ .* θ)


function dldθ(θ)
    x,lambda = Flux.Zygote.pullback(l,θ)
    grad = first(lambda(1))
    return x, grad
end

metric  = DiagEuclideanMetric(length(prob_neuralode.p))

h = Hamiltonian(metric, l, dldθ)


integrator = Leapfrog(find_good_stepsize(h, Float64.(prob_neuralode.p)))


prop = AdvancedHMC.NUTS{MultinomialTS, GeneralisedNoUTurn}(integrator)

adaptor = StanHMCAdaptor(MassMatrixAdaptor(metric), StepSizeAdaptor(0.45, prop.integrator))

samples, stats = sample(h, prop, Float64.(prob_neuralode.p), 500, adaptor, 500; progress=true)


losses = map(x-> x[1],[loss_neuralode(samples[i]) for i in 1:length(samples)])
```
that I took from this GitHub `https://github.com/RajDandekar/MSML21_BayesianNODE`, but it raise this error:

```
type HMCKernel has no field integrator

Stacktrace:
 [1] getproperty(x::HMCKernel{AdvancedHMC.FullMomentumRefreshment, Trajectory{MultinomialTS, Leapfrog{Float64}, GeneralisedNoUTurn{Float64}}}, f::Symbol)
   @ Base ./Base.jl:33
 [2] top-level scope
   @ In[10]:52
 [3] eval
   @ ./boot.jl:360 [inlined]
 [4] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1116
```
in other example I'm trying to run the error is:

```
MethodError: no method matching GeneralisedNoUTurn(::Int64)
Closest candidates are:
  GeneralisedNoUTurn(::Int64, ::F) where F<:AbstractFloat at ~/.julia/packages/AdvancedHMC/yd6UP/src/trajectory.jl:391
  GeneralisedNoUTurn(; max_depth, Δ_max) at util.jl:461
  GeneralisedNoUTurn(::StrictGeneralisedNoUTurn) at ~/.julia/packages/AdvancedHMC/yd6UP/src/trajectory.jl:411

Stacktrace:
 [1] NUTS{MultinomialTS, GeneralisedNoUTurn}(int::Leapfrog{Float64}, args::Int64; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ AdvancedHMC ~/.julia/packages/AdvancedHMC/yd6UP/src/AdvancedHMC.jl:64
 [2] NUTS{MultinomialTS, GeneralisedNoUTurn}(int::Leapfrog{Float64}, args::Int64)
   @ AdvancedHMC ~/.julia/packages/AdvancedHMC/yd6UP/src/AdvancedHMC.jl:64
 [3] top-level scope
   @ In[8]:61
 [4] eval
   @ ./boot.jl:360 [inlined]
 [5] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base ./loading.jl:1116
```
Somebody knows why this happens? Is it a conflict between packages and the version of Julia I'm using?
None of the scripts that I run from the GitHub cited above is working. I would appreciate some advice in order to fix this.

**Comment by ChrisRackauckas** [comment]
HMCKernel doesn't exist in this package.

**Comment by ChrisRackauckas** [comment]
@RajDandekar

**Comment by RajDandekar** [comment]
Can you try replicating the code on the AdvancedHMC page: 

`using AdvancedHMC, Distributions, ForwardDiff
using LinearAlgebra

# Choose parameter dimensionality and initial parameter value
D = 10; initial_θ = rand(D)

# Define the target distribution
ℓπ(θ) = logpdf(MvNormal(zeros(D), I), θ)

# Set the number of samples to draw and warmup iterations
n_samples, n_adapts = 2_000, 1_000

# Define a Hamiltonian system
metric = DiagEuclideanMetric(D)
hamiltonian = Hamiltonian(metric, ℓπ, ForwardDiff)

# Define a leapfrog solver, with initial step size chosen heuristically
initial_ϵ = find_good_stepsize(hamiltonian, initial_θ)
integrator = Leapfrog(initial_ϵ)

# Define an HMC sampler, with the following components
#   - multinomial sampling scheme,
#   - generalised No-U-Turn criteria, and
#   - windowed adaption for step-size and diagonal mass matrix
proposal = NUTS{MultinomialTS, GeneralisedNoUTurn}(integrator)
adaptor = StanHMCAdaptor(MassMatrixAdaptor(metric), StepSizeAdaptor(0.8, integrator))

# Run the sampler to draw samples from the specified Gaussian, where
#   - `samples` will store the samples
#   - `stats` will store diagnostic statistics for each sample
samples, stats = sample(hamiltonian, proposal, initial_θ, n_samples, adaptor, n_adapts; progress=true)`

**Comment by RajDandekar** [comment]
This code above has many similar components to the Bayesian NODE NUTS code.

**Comment by tortijazz** [comment]
Ok, @RajDandekar. I'm gonna replicate that code and I will tell you. Thank you both.

**Comment by tortijazz** [comment]
Hi again,
For some reason removing `AdvancedHMC.` form `AdvancedHMC.NUTS...` and `prop.` from `prop.integrator` the code works perfectly. The code here `https://github.com/TuringLang/AdvancedHMC.jl` gave me the answer. Thank you, @RajDandekar.
