### ISSUE TITLE
Migrate to new style test-setup

### ISSUE THREAD

**Issue by prbzrg** [SciML/DiffEqFlux.jl#626]
According to [`Pkg.jl` documentations](https://pkgdocs.julialang.org/v1/creating-packages/#Adding-tests-to-the-package), there are two ways to specify the dependencies for tests:

1. new style test-setup (Julia v1.2+): have 'test/Project.toml'
2. old style test-setup (Julia v1.0-v1.1): have `[targets]` section in `Project.toml`

As I see, `DiffEqFlux.jl` uses old style.
Should we migrate to new style? (I think we can have both, but I prefer not)

**Comment by ChrisRackauckas** [comment]
SciML should update to the new style, we just need someone to find the time to do it.
