### ISSUE TITLE
tests failing with MethodError: _axes(::StrideArraysCore

### ISSUE THREAD

**Issue by CarloLucibello** [SciML/DiffEqFlux.jl#646]
Tests are currently failing, the stack trace can be found here 
https://github.com/SciML/SciMLBase.jl/runs/4049107830?check_suite_focus=true#step:6:1030

**Comment by ChrisRackauckas** [comment]
@chriselrod https://github.com/SciML/SciMLBase.jl/runs/4049107830?check_suite_focus=true#step:6:1030

**Comment by ChrisRackauckas** [comment]
Also @Tokazama

**Comment by ChrisRackauckas** [comment]
Should be fixed by https://github.com/JuliaSIMD/StrideArraysCore.jl/compare/v0.2.7...v0.2.8

**Comment by chriselrod** [comment]
Yeah, should be fixed now.

**Comment by Tokazama** [comment]
Sorry about this. I didn't think `ArrayInterface._axes` was being used outside of `ArrayInterface.jl` method might be used elsewhere.
