### ISSUE TITLE
WARNING: could not import DistributionsAD._mv_categorical_logpdf into ReverseDiffX

### ISSUE THREAD

**Issue by TravellingLight6** [SciML/DiffEqFlux.jl#649]
The issue manifests itself as the title. Currently, I installed DiffEqFlux@v1.23.0 in my julia and keep getting this annoy message. And I don't whether due to this I cannot run the [demo code](https://diffeqflux.sciml.ai/dev/examples/neural_ode_sciml/) but get the error, saying "ERROR: LoadError: UndefKeywordError: keyword argument lower_bounds not assigned". Any help would be appreaciated!!

**Comment by ChrisRackauckas** [comment]
Use the latest version v1.44.0. I assume there's some dependency that is screwing things up.
