### ISSUE TITLE
Reproducibility on different operating systems

### ISSUE THREAD

**Issue by stefan-m-lenz** [SciML/DiffEqFlux.jl#655]
We put together some code that trains a neural ODE model on simulated data:

https://github.com/stefan-m-lenz/SpiralReproducibilityTest

The model is also described in the following article: https://arxiv.org/abs/2005.06334

The issue is that the results of the code, which uses `DiffEqFlux`, are not reproducible across different systems, although a `Manifest.toml` file is used to ensure that the package versions are identical.
The results are reproducible on the same system, though.

On Windows, I get the following output when running `julia ExecuteInJulia.jl` (using Julia 1.6.3):
```
Epoch 1: 1.2049182037881969e7
Epoch 2: 9.119434772960356e6
Epoch 3: 6.111235935211631e6
Epoch 4: 3.4831750092791957e6
Epoch 5: 3.4031234428792936e6
```

On Ubuntu 20.04 (same machine as Windows, dual boot, also Julia 1.6.3):
```
Epoch 1: 1.2049189168263948e7
Epoch 2: 9.119154236157099e6
Epoch 3: 6.146511675285868e6
Epoch 4: 3.0688250849567153e6
Epoch 5: 2.5683954370382177e6
```

On Debian 10 (different machine, also with Julia 1.6.3) the output is:
```
Epoch 1: 1.2049178682925774e7
Epoch 2: 9.1206591017266e6
Epoch 3: 5.963402953805998e6
Epoch 4: 3.2126556587542454e6
Epoch 5: 2.3087342534360127e6
```

Can someone explain this behaviour?

**Comment by stefan-m-lenz** [comment]
The only hint that different results are obtained in Julia on different systems is this post:

https://discourse.julialang.org/t/same-code-very-different-results-with-julia-1-4-2-and-julia-1-5-2/47416/19

**Comment by ChrisRackauckas** [comment]
Yeah that's not surprising. LLVM and BLAS implementations will optimize differently on different operating systems. And it can also be due to threading. So I'll close this because it has nothing to do with DiffEqFlux but instead is lower in the matrix multiplication and other intrinsics,
