### ISSUE TITLE
Missing optimizations in preallocation form

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#680]
```julia
using DiffEqFlux, OrdinaryDiffEq, Flux, Optim, Plots, DiffEqSensitivity,
      Zygote, BenchmarkTools, Random

u0 = Float32[2.0; 0.0]
datasize = 30
tspan = (0.0f0, 1.5f0)
tsteps = range(tspan[1], tspan[2], length = datasize)

function trueODEfunc(du, u, p, t)
    true_A = [-0.1 2.0; -2.0 -0.1]
    du .= ((u.^3)'true_A)'
end

prob_trueode = ODEProblem(trueODEfunc, u0, tspan)
ode_data = Array(solve(prob_trueode, Tsit5(), saveat = tsteps))

dudt2 = FastChain((x, p) -> x.^3,
                  FastDense(2, 50, tanh, precache=true),
                  FastDense(50, 2, precache=true))
Random.seed!(100)
p = initial_params(dudt2)

prob_neuralode = NeuralODE(dudt2, tspan, Tsit5(), saveat = tsteps)

function loss_neuralode(p)
    pred = Array(prob_neuralode(u0, p))
    loss = sum(abs2, ode_data .- pred)
    return loss
end

@btime Zygote.gradient(loss_neuralode,p)


using Profile
@profile Zygote.gradient(loss_neuralode,p)
Juno.profiler()
```

Points mostly to:

https://github.com/SciML/DiffEqFlux.jl/blob/d98b449cf18b7b439faabcd5f8b0db4d311fb65e/src/fast_layers.jl#L142

`vcat` of course allocates which is where the remaining allocations from https://github.com/SciML/DiffEqFlux.jl/pull/679 seem to come form. Next is `generic_matmul`'s 

```julia
    if tile_size > 0
        sz = (tile_size, tile_size)
        Atile = Array{T}(undef, sz)
        Btile = Array{S}(undef, sz)
```

@chriselrod does Octavian.jl avoid these?

Then there is the Zygote adjoint broadcast allocation, which is specific to `(x, p) -> x.^3` so that can be ignored.

**Comment by chriselrod** [comment]
> @chriselrod does Octavian.jl avoid these?

Yes. It does one of two things:
1. For tiles smaller than the L2 cache size on x64 systems, it stack allocates an L2 cache size block.
2. Else, it uses a pre-allocated global memory buffer.

**Comment by Abhishek-1Bhatt** [comment]
> It seems like the cache should only be holding pbar, and define Wbar and bbar as the appropriate views of pbar.

There's an improvement with this implemented:

![WhatsApp Image 2022-02-06 at 9 31 03 PM (1)](https://user-images.githubusercontent.com/46929125/152689676-f1f91b8b-1a86-40ab-9ff5-0a134c188bbe.jpeg)

![WhatsApp Image 2022-02-06 at 9 31 03 PM](https://user-images.githubusercontent.com/46929125/152689685-d0143d43-d864-47c2-8373-648b0cb8a55d.jpeg)

**Comment by ChrisRackauckas** [comment]
Just paste the text instead of the screenshots, it's so odd 😅

**Comment by ChrisRackauckas** [comment]
See SimpleChains.jl
