### ISSUE TITLE
PINN with TensorLayer example fails - maybe Enzyme internal error

### ISSUE THREAD

**Issue by stephans3** [SciML/DiffEqFlux.jl#694]
I tried to run the [PINN with TensorLayer](https://diffeqflux.sciml.ai/stable/examples/tensor_layer/) example with Julia 1.6.5 and 1.7.2 but the execution fails and kills the Julia instance.

The error occurs at `res1 = DiffEqFlux.sciml_train(...)`
It seems that Enzyme throws some errors. [The full error message can be found here](https://gist.github.com/stephans3/6c1f19bcaae2adfb242be7bd611d3562).

I have also tested the [Optimization of Ordinary Differential Equations example](https://diffeqflux.sciml.ai/stable/examples/optimization_ode/) which works properly. 

```shell
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
```

```julia
pkg> status
      Status `~/.julia/environments/v1.6/Project.toml`
[aae7a2af] DiffEqFlux v1.45.3
[0c46a032] DifferentialEquations v7.1.0
[587475ba] Flux v0.12.9
[429524aa] Optim v1.6.2
```

```shell
Julia Version 1.7.2
Commit bf53498635 (2022-02-06 15:21 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-12.0.1 (ORCJIT, skylake)
```

```julia
pkg> status
   Status `~/.julia/environments/v1.7/Project.toml`
  [aae7a2af] DiffEqFlux v1.45.3
  [0c46a032] DifferentialEquations v7.1.0
  [587475ba] Flux v0.12.9
  [429524aa] Optim v1.6.2
```

**Comment by ChrisRackauckas** [comment]
I may have just solved this earlier today. Make sure you update and get Enzyme v0.9.

**Comment by stephans3** [comment]
The latest versions of Flux and DiffEqFlux does not seem to work together with Enzyme v0.9.x

My steps:
1. added Enzyme to environment in version 0.8.5
2. updated the Registry [as described here](https://pkgdocs.julialang.org/v1/registries/)
3. removed DiffEqFlux and Flux; and updated Enzyme to v0.9.2
4. added again DiffEqFlux / Flux: Enzyme was downgraded to v0.8.5 

So I am not able to run DiffEqFlux or Flux together with Enzyme v0.9.x

**Comment by ChrisRackauckas** [comment]
CUDA.jl does not seem to allow the latest Enzyme. A release with https://github.com/JuliaGPU/CUDA.jl/commit/71e9760f02bc6e1bc76aaaf32e98be10a41bae6b would be required (@maleadt)

**Comment by maleadt** [comment]
Yes, I'm waiting for a new 1.8 beta/rc to validate things first. So not this week probably.

**Comment by ChrisRackauckas** [comment]
Solved.
