### ISSUE TITLE
Incorrect use `Lux.ActivationFunction`

### ISSUE THREAD

**Issue by avik-pal** [SciML/DiffEqFlux.jl#737]
The updated docs have used `ActivationFunction` in https://diffeqflux.sciml.ai/dev/examples/neural_ode/ (and possibly other places). Note that the semantics of ActivationFunction is different from the intended use case -- See http://lux.csail.mit.edu/stable/api/layers/#Lux.WrappedFunction vs http://lux.csail.mit.edu/stable/api/layers/#Lux.ActivationFunction (the intention of having this layer was to allow a very rudimentary implementation of layer fusion, which I might still implement later on)

Additionally, this should not be done, since http://lux.csail.mit.edu/stable/api/layers/#Lux.Chain will automatically do it for the user (and IMO makes code less clunky)

**Comment by Abhishek-1Bhatt** [comment]
Should we switch to `WrappedFunction` in the docs then?

**Comment by avik-pal** [comment]
No no. Just remove any wrapper, Chain will do it on its own.

**Comment by Abhishek-1Bhatt** [comment]
Oh, yeah it returns it as a `WrappedFunction` by default
