### ISSUE TITLE
Move AD Rules to `SciMLSensitivity`

### ISSUE THREAD

**Issue by prbzrg** [SciML/DiffEqFlux.jl#744]
https://github.com/SciML/DiffEqFlux.jl/blob/e32422d86bea1cdda8797d0b909cb3e207738bd5/src/DiffEqFlux.jl#L24-L40

Related to https://github.com/SciML/SciMLSensitivity.jl/issues/582

**Comment by ChrisRackauckas** [comment]
Those rules should just be removed or upstreamed. @oxinabox @DhairyaLGandhi are any of those required these days?

**Comment by prbzrg** [comment]
What's update on this?

**Comment by ChrisRackauckas** [comment]
Tridiagonal rules moved with https://github.com/JuliaDiff/ChainRules.jl/pull/758

**Comment by ChrisRackauckas** [comment]
Oh, these all were removed awhile ago.
