### ISSUE TITLE
Problems defined by parametric and neural network functions

### ISSUE THREAD

**Issue by raphaelchinchilla** [SciML/DiffEqFlux.jl#746]
In the article [Universal Differential Equations for Scientific Machine Learning](https://arxiv.org/pdf/2001.04385.pdf), it is described a problem in which an ODE is defined by a combination of parametric functions and neural network (equation 3). My questions are:

- I could not find in the documentation of DiffEqFlux how to do this. (I was able to write it manually and then call an ODEProblem in the function, but I presume there is a better way to do it)
- I wanted to do the same thing but for a DAE with dynamics described by a combination of parametric functions and neural networks. To be more clear, I know the NeuralDAE and NeuralODEMM can be used to define a DAE described by a neural network, but I want a problem described by both a parametric function and neural network.
- Bonus question: It is not very clear what is the difference between NeuralDAE and NeuralODEMM

**Comment by ChrisRackauckas** [comment]
> Bonus question: It is not very clear what is the difference between NeuralDAE and NeuralODEMM

It's the difference between `Mu' = f(u)` vs `0 = f(du,u)`. The latter is more general, the former is many times called a linearly-implicit DAE, where it's equivalent to the case that `df/d(du) = M` is a constant. There's a lot to say about DAEs, like differential index and such, but one clear thing is that linearly implicit DAEs are a much nicer constrained space, and so it seems to be much more promising than the fully implicit case with neural networks.

**Comment by raphaelchinchilla** [comment]
@ChrisRackauckas thanks for the explanation.

Two things:
- NeuralDAE does not have a dispatch for Lux and FastChain models. I am not sure whether this is on purpose.
- By the way that NeuralODEMM is presented, it seems that one has to define both the mass matrix AND the constraints model. Intuitively, it seems weird that both need to be specified.

**Comment by ChrisRackauckas** [comment]
NeuralDAE is still pretty experimental. It hasn't found a use case that wasn't better suited by linearly implicit right now.

The MM can still do non-trivial things, i.e. it's not necessarily just identity and zero rows.
