### ISSUE TITLE
Remove multiple shooting and collocation

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqFlux.jl#773]
With a lot of the optimization functionality of this package being moved to Optimization.jl,
I wonder if the multiple shooting and collocation tutorials should be using DiffEqParameterEstim?
If that is done only the layers remain here.

**Comment by ChrisRackauckas** [comment]
The functionality doesn't quite fit into DiffEqParamEstim.jl which is a much more constrained interface, which is separate from this package which is just "define your own loss function" layers. Yes, they don't have a great place to live but here might be the best of bad decisions.

**Comment by ArnoStrouwen** [comment]
So do you suggest removing multiple shooting and collocation from DiffEqParameterEstim?
The code here is pretty much a copy paste from the code there.
I think it is very confusing to have the exact same functionality in two places.
