### ISSUE TITLE
Forward over reverse broken

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/DiffEqFlux.jl#776]
Currently forward over reverse tests are broken.
https://github.com/SciML/DiffEqFlux.jl/blob/master/test/newton_neural_ode.jl
The test pass by deleting
https://github.com/avik-pal/Lux.jl/blob/e610076cd1b0d1b8338cbee21e443791b7aef00b/src/autodiff.jl#L36-L47
But even with this deletion I'm not sure the hessian is correct.

In the forward pass `x` is weirdly not a dual type, but in the reverse pass `dy` has regained the partials somehow. 
Converting `dy` into `dx` based on the type `x` of then throws an error.

**Comment by avik-pal** [comment]
Can you open a PR in Lux deleting that? If all the tests pass we can merge it. I am not sure why it was needed in the first place
