### ISSUE TITLE
Wrong order in collocations

### ISSUE THREAD

**Issue by axla-io** [SciML/DiffEqFlux.jl#788]
https://github.com/SciML/DiffEqFlux.jl/blob/ccc3dcd0ccb7c18a176fc30dc9cb964acf98d50b/src/collocation.jl#L158

This line should be 
`du, u = collocate_data(reshape(data, 1, :),tpoints,tpoints_sample,interp,args...)`

**Comment by ChrisRackauckas** [comment]
definitely.

**Comment by ChrisRackauckas** [comment]
How was that passing tests...

**Comment by axla-io** [comment]
Yeah that's pretty surprising
