### ISSUE TITLE
Documentation about Flux.jl vs Lux.jl

### ISSUE THREAD

**Issue by schlichtanders** [SciML/DiffEqFlux.jl#815]
Hi,
the README on github already states that both Flux and Lux are supported. Also some examples (I found at least one) are already using Lux.

I heard that Lux.jl is the preferred framework for Differential Equations, but cannot easily find a reference backing this.

Can someone from DiffEqFlux.jl summarize why both Flux.jl and Lux.jl are supported and what the difference between those two is with respect to Differential Equations?

I think the DiffEqFlux.jl documentation would be a perfect place for such a comparison.

**Comment by ChrisRackauckas** [comment]
See https://github.com/SciML/DiffEqFlux.jl/pull/819/files. I hate to be the bearer of bad news but there's some very clear examples (as shown with linked issues that have multiple MWEs) where it shows why we moved our tests from Flux.jl to Lux.jl, as Flux.jl was found to break tests in tons of separate occasions or had the wrong precision in unclear ways. Changing from Flux to Lux fixed all of those issues, so we highly recommend everyone else do the same.

**Comment by ChrisRackauckas** [comment]
I did not know Lux.transform exists. That's a great option to make use of.

**Comment by prbzrg** [comment]
I can make a PR, if that's desirable.

**Comment by ChrisRackauckas** [comment]
That would be great.
