### ISSUE TITLE
What to do about FFJORD here?

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/DiffEqFlux.jl#816]
@prbzrg I saw your https://github.com/impICNF/ICNF.jl which seems to have a lot of FFJORD things, should FFJORD and all just be a whole separate repo and pull that into SciML? If you have things in good shape then I would prefer to just reuse that code and then make sure any GSoC is implementing algorithms separate from that.

**Comment by prbzrg** [comment]
Thanks for your attention, I will be glad to move it to SciML.
The API is good, and I don't have any plan to change it.
The documentation is poor, but the amount of function to be documented is a few.
The performance is similar to `DiffEqFlux`.
There are smoke tests, but we need some regression tests.
