### ISSUE TITLE
UODE with neural networks. Beginner questions

### ISSUE THREAD

**Issue by user161715** [SciML/DiffEqFlux.jl#831]
Hello developers,

I am new to `Julia`, `UODE` and `sciML`. 

So I have a few basic questions which I would like to clarity:

1. Where can I ask question related to `sciML`? Is the `Issues` section of this github appropriate? 
2. Are there any video tutorial on how to set up and train `UODE`'s with the sciML package?
3. Is there any example using `neuralODE`'s with `UODE`? In the `Lotka-Volterra` system in https://github.com/ChrisRackauckas/universal_differential_equations/blob/master/LotkaVolterra/scenario_1.jl its appears to be a feed-forward NN (Or am I wrong?)
4.  What does this means in Julia `nn_dynamics!(du,u,p,t) = ude_dynamics!(du,u,p,t,p_)`. A function with parameters equal to another function with parameters.

Thank you for developing this package. I have a problem with 5 dimensions (dx_1,dx_2,dx_3,dx_4, dx_5) where I only know part of the physics but have a tone of data.  
This package seems to be right tool to model the information the physical model is not capturing.

Best Regards,
James

**Comment by prbzrg** [comment]
Hi, Happy to see a newcomer

1. For general questions, Julia forum is the best way to get help. And it has a section for specific domains.
https://discourse.julialang.org/c/domain/10
2. There is an online book that can help you see and learn tools and APIs of SciML.
https://book.sciml.ai/
3. To know the details of UODE, see the citations of this package.
https://github.com/SciML/DiffEqFlux.jl/blob/master/CITATION.bib
4. It's a way to define a function, To know more about functions in Julia, see the official manual of it at 
https://docs.julialang.org/en/v1/manual/functions/

**Comment by prbzrg** [comment]
Hi, Happy to see a newcomer

1. For general questions, Julia forum is the best way to get help. And it has a section for specific domains.
https://discourse.julialang.org/c/domain/10
2. There is an online book that can help you see and learn tools and APIs of SciML.
https://book.sciml.ai/
3. To know the details of UODE, see the citations of this package.
https://github.com/SciML/DiffEqFlux.jl/blob/master/CITATION.bib
4. It's a way to define a function, To know more about functions in Julia, see the official manual of it at 
https://docs.julialang.org/en/v1/manual/functions/

**Comment by ChrisRackauckas** [comment]
Feel free to ask more questions, but closing since it seems answered.
