### ISSUE TITLE
Q about use of UDEs

### ISSUE THREAD

**Issue by sophia-wright-blue** [SciML/DiffEqFlux.jl#836]
hello - I have a very basic question: 

the paper UDE for SciML lists this library for UDE training schemes - I don't see UDE listed separately in the Table of Contents though - I was hoping to pull up the relevant code for the different sections in the paper to understand it better - could you please guide me to the connection between the paper and this library please - thank you

**Comment by ChrisRackauckas** [comment]
Hey sorry I missed this one. There was a reorganization of the libraries a little bit back. It's mentioned in the documentation:

> DiffEqFlux.jl is only for pre-built architectures and utility functions for deep implicit learning, mixing differential equations with machine learning. For details on automatic differentiation of equation solvers and adjoint techniques, and using these methods for doing things like calibrating models to data, nonlinear optimal control, and PDE-constrained optimization, see [SciMLSensitivity.jl](https://docs.sciml.ai/SciMLSensitivity/stable/)

You'll find UDE examples there and in the SciML Showcase.

https://docs.sciml.ai/Overview/stable/showcase/missing_physics/
