### ISSUE TITLE
FR: Second-Order Neural ODE Optimizer

### ISSUE THREAD

**Issue by prbzrg** [SciML/DiffEqFlux.jl#849]
I just found this paper, maybe it would be good to have it.

https://arxiv.org/abs/2109.14158

https://proceedings.neurips.cc/paper_files/paper/2021/hash/d4c2e4a3297fe25a71d030b67eb83bfc-Abstract.html

**Comment by ChrisRackauckas** [comment]
Yes, that's the same as https://docs.sciml.ai/SciMLSensitivity/stable/examples/ode/second_order_adjoints/ with backsolve adjoint. It's also O(1) memory etc. because it's the same algorithm. I'm surprised someone would write a paper about it since it's an algorithm from a long time back.
