### ISSUE TITLE
Restructuring some of the Layers

### ISSUE THREAD

**Issue by avik-pal** [SciML/DiffEqFlux.jl#929]
**Question❓**

What do we feel about moving some of the non-diffeq specific layers to `Boltz.jl` and re-exporting them from here?

I was working on implementing KANs and we might be able to reuse the Spline Layers from here, but DiffEqFlux has too heavy deps (not complaining here, it needs to). Boltz.jl on the other hand is quite lightweight, only pulling in stdlibs and Lux (and some other smallish packages).

**Comment by ChrisRackauckas** [comment]
Yeah go for it.

**Comment by avik-pal** [comment]
Most layers are now part of Boltz. Spline Layer will be added in https://github.com/LuxDL/Boltz.jl/pull/35.
